<?php

/*
	[12IK] (C) 2012-2015 12IK.COM
	$Id: admincp.lang.php 13493 2009-11-11 06:15:33Z charm $
*/

//if(!defined('IN_SUPESITE')) exit('Access Denied');

$alang = array(
	//admin/admin_ad.php,
	'common_submit' => '提交保存',
	'common_reset' => '重置',
	'ad_title_view' => '站点广告管理',
	'ad_title_add_system' => '添加系统广告',
	'ad_title_add_user' => '添加自定义广告',
	'ad_title_adcode' => '调用代码',
	'ad_title_explain' => '说明:请复制文本框中的代码，并将代码添加到站点的模板文件的适当位置，即可显示您设置的广告内容。',
	'ad_title_adshow' => '效果预览',
	'ad_delete' => '删除',
	'ad_available' => '可用',
	'ad_displayorder' => '显示顺序',
	'ad_style' => '样式',
	'ad_system' => '系统内置广告',
	'ad_type' => '投放频道',
	'ad_type_all' => '全部频道',
	'ad_page' => '投放页面',
	'ad_show' => '展现方式',
	'ad_add_adtype' => '添加广告',
	'ad_adtype_code' => '广告代码',
	'ad_adtype_js_code' => '广告代码<p>(填写的Javascript代码中不能有任何的注释表示符)</p>',
	'ad_available_all' => '全部可用',
	'help_ad_view' => '<ul>
			<li>您可以添加不同格式的广告，包括直接显示、JavaScript调用、iframe调用等格式。</li>
			<li>通过点击<u>广告代码</u>链接，您可以获取指定广告的显示代码，请将该代码复制，并放置于站点模板文件要显示广告的位置，就可以显示您指定的广告了。</li>
			<li>投放频道说明:indexad为综合聚合页面, news为资讯频道, 如果安装了uchome, 则uchblog为uch日志频道, uchimage为uch相册频道</li>
			<li>投放页面说明: 1 为1级页面, 2 为2级页面, 3 为查看页面</li>
			<li>页面中央横幅广告，在内容查看页时，显示在文章底部</li>
			</ul>',
	'ad_title_choose' => '选择',
	'ad_title_subject' => '标题',
	'ad_title_type' => '广告类型',
	'ad_title_dateline' => '发布时间',
	'ad_title_endtime' => '结束时间',
	'ad_title_operate' => '操作',
	'ad_adtype_detail' => '编辑',
	'ad_adtype_echo' => '直接显示',
	'ad_adtype_js' => 'Javascript调用',
	'ad_adtype_iframe' => 'iframe调用',
	'ad_adtype_text' => '文本',
	'ad_adtype_image' => '图片',
	'ad_adtype_flash' => 'FLASH',
	'ad_adtype_page_one' => '一级页面',
	'ad_adtype_page_two' => '二级页面',
	'ad_adtype_page_view' => '查看页面',
	'ad_adtype_all_page' => '频道全部广告位',
	'ad_adtype_index_page' => '首页聚合页面',
    'ad_adtype_space' => '个人查看页面',
	'ad_adtype_pageheadad_page' => '页面顶部广告',
	'ad_adtype_pagecenterad_page' => '页面中央横幅广告',
	'ad_adtype_pagefootad_page' => '页面底部广告',
	'ad_adtype_pagemovead_page' => '页面对联广告',
	'ad_adtype_pageoutad_page' => '页面漂浮广告',
	'ad_adtype_pageoutindex_page' => '页面弹出广告',
	'ad_adtype_siderad' => '页面侧边广告',
	'ad_adtype_viewinad' => '内容查看广告',
	'ad_adtype_iframewidth' =>'Iframe高度(必填,单位px):',
	'ad_adtype_iframeheight' => 'Iframe宽度(必填,单位px):',
	'ad_adtype_textcontent' => '文字内容(必填):',
	'ad_adtype_texturl' => '文字链接(必填):',
	'ad_adtype_textsize' => '文字大小(必填,大小不能为0,单位px):',
	'ad_adtype_imagesrc' => '图片地址',
	'ad_adtype_imageurl' => '图片链接(必填):',
	'ad_adtype_imagewidth' => '图片宽度(必填,单位px):',
	'ad_adtype_imageheight' => '图片高度(必填,单位px):',
	'ad_adtype_imagetext' => '图片替换文字(选填):',
	'ad_adtype_flashsrc' => 'Flash 地址(必填):',
	'ad_adtype_flashwidth' => 'Flash 宽度(必填,单位px):',
	'ad_adtype_flashheight'=>'Flash 高度(必填,单位px):',
	'ad_pageout_width' => '弹出广告位的宽度(必填,单位px):',
	'ad_pageout_height' => '弹出广告位的高度(必填,单位px):',
	'space_edit' => '编辑',
	'space_select_all' => '全选',
	'help_ad_add' => '<ul>
			<li>如果您要设置的广告代码里面包含JavaScript语句，请使用直接显示、或者iframe调用格式，不要使用JavaScript调用格式，否则可能会导致广告无法显示。</li>
			<li>如果是新添加的广告，那么，请您在添加完毕后，通过列表页面的<u>广告代码</u>链接，获取本广告显示代码，并放置于站点模板文件要显示广告的位置后，才可以显示您新添加的广告。</li>
			</ul>',

	//admin/admin_admincp_sidemenu.php,
	'admincp_header_channel' => '功能频道设置',
	'admincp_site_set' => '站点设置',
	'model_export' => '导出',
	'admincp_html_opening' => 'HTML启用',
	'html_manual_generation' => 'HTML手工生成',
	'management_theme' => '主题管理',
	'management_comments' => '评论管理',
	'management_model' => '模型管理',
	'new_model' => '新建模型',
	'model_field' => '字段',
	'authority_management' => '权限管理',
	'import_model' => '导入模型',
	'release_information' => '发布信息',
	'classified_management' => '分类管理',
	'pending_box_management' => '待审箱管理',
	'waste_management_bins' => '废件箱管理',
	'block_add' => '创建模块',
	'spacenews_add' => '发布资讯',
	'admincp_header_check' => '等级审核',
	'check_view_all' => '全部',
	'common_type_news' => '资讯',
	'common_type_blog' => '日志',
	'common_type_image' => '图片',
	'admincp_header_type_bbsforums' => '论坛版块聚合设置',
	'admincp_header_type_bbsset' => '论坛聚合设置',
	'admincp_header_type_bbsthreads' => '论坛帖子批量聚合',

	'uchome_set' => 'UCenter Home 设置',
	'poll_add' => '添加投票',
	'poll_view_list' => '浏览投票',
	'admincp_header_tpl_list' => '站点模板',
	'admincp_header_css' => '站点样式表',
	'cron_view_list' => '浏览计划任务',
	'cron_add' => '添加计划任务',
	'admincp_header_else' => '其他管理',
	'announcements_title' => '公告管理',	
	'admincp_header_html' => 'HTML静态配置',
	'smart_acquisition' => '智能采集',
	'batch_management_theme' => '批量主题管理',
	'robot_url' => '采集的URL',
	'import_model_suc' => '导入模型成功',

	//admin/admin_admincp_toolbar.php,
	'bbs_setting' => '聚合相关设置',

	//admin/admin_announcements.php,
	'announcements_list' => '公告列表',
	'announcements_overdue_list' => '过期公告列表',
	'spaceannouncements_title_announcementsurl' => '外部链接URL<p>如果填入外部链接，查看该公告时，将自动跳转到该链接。</p>',
	'announcements_add' => '新增公告',
	'help_announcements' => '<ul>
			<li>您可以使用站点公告来将某件事情通知站内的访问者。</li>
			</ul>',
	'announcements_select' => '选择',
	'announcements_author' => '作者',
	'announcements_subject' => '标题',
	'announcements_starttime' => '起始时间',
	'announcements_endtime' => '终止时间',
	'announcements_displayorder' => '显示顺序',
	'announcements_option' => '操作',
	'poll_delete' => '删除',
	'announcements_no_limit' => '不限制',
	'announcements_endtime_message' => '结束时间<p>留空为不限制</p>',
	'announcements_message' => '公告内容',

	//admin/admin_attachments.php,
	'block_select' => '选择',
	'annex_name' => '附件名',
	'annex_size' => '附件大小',
	'space_order_dateline' => '发布时间',

	//admin/admin_attachmenttypes.php,
	'attachmenttype_title' => '附件类型',
	'attachmenttype_view_list' => '查看文件类型',
	'attachmenttype_add' => '添加文件类型',
	'help_attachmenttypes' => '<ul>
			<li>在文件类型中列出的文件名后缀，是您的站点允许用户上传的文件类型和允许上传的最大尺寸</li>
			<li>没有被列出的文件类型，将不允许上传</li>
			</ul>',
	'attachmenttype_fileext' => '文件后缀名',
	'attachmenttype_maxsize' => '大小限制',
	'attachmenttype_op' => '操作',
	'attachmenttype_maxsize_0' => '禁止上传',
	'space_delete' => '删除',
	'attachmenttype_maxsize_0_5' => '0.5 MB',
	'attachmenttype_maxsize_1' => '1.0 MB',
	'attachmenttype_maxsize_1_5' => '1.5 MB',
	'attachmenttype_maxsize_2' => '2.0 MB',

	//admin/admin_bbsforums.php,
	'bbsforums_view' => '论坛版块',
	'bbsforums_status_uc' => '是否允许导入',
	'bbsforums_view' => '论坛版块',
	'bbsforums_status_0' => '不收录',
	'bbsforums_status_1' => '自动',
	'bbsforums_status_2' => '手工',
	'bbsforums_status_3' => '智能',
	'help_bbsforums' => '<ul>
			<li>您通过本设置，可以设置论坛版块在SupeSite站点页面上的显示时的别名、以及版块内帖子的收录模式</li>
			<li>收录帖子三种模式：</li>
			<li>自动：收录全部主题</li>
			<li>智能：通过设定的条件收录主题</li>
			</ul>',
	'bbsforums_new_name' => '站点显示别名',
	'bbsforums_allowshare' => '显示',
	'bbsforums_supe_pushsetting' => '收录帖子模式',
	'bbsforums_title_displayorder' => '显示顺序',
	'common_edit' => '编辑',
	'common_copy' => '复制',
	'bbsforums_views' => '查 看 数',
	'bbsforums_replies' => '回 复 数',
	'bbsforums_digest' => '精华级别',
	'bbsforums_digest1' => '精华I',
	'bbsforums_digest2' => '精华II',
	'bbsforums_digest3' => '精华III',
	'bbsforums_displayorder' => '置顶级别',
	'bbsforums_displayorder1' => '置顶I',
	'bbsforums_displayorder2' => '置顶II',
	'bbsforums_displayorder3' => '置顶III',
	'bbs_block_set' => '论坛版块设置',

	//admin/admin_bbs.php
	'bbs_setting_info' => '论坛参数配置',
	'bbs' => '论坛',

	//admin/admin_threads.php
	'bbs_threas_set' => '论坛主题手工收录',

	//admin/admin_uchome.php
	'uchome_setting' => 'UCenter Home参数配置',
	'uchblog' => '日志',
	'uchimage' => '相册',

	//admin/admin_bbs.php
	'bbs_setting_info' => '论坛参数配置',

	//admin/admin_threads.php
	'bbs_threas_set' => '论坛主题手工收录',

	//admin/admin_uchome.php
	'uchome_setting' => 'UCenter Home参数配置',

	//admin/admin_blocks.php,
	'block_title' => '模块',
	'block_table' => '表名',
	'block_view_list' => '浏览模块',
	'help_blocks_view' => '<ul>
			<li>请选择现有的模板代码，根据自己的需要，添加到站点模板文件的任意位置中，便可以实现对论坛、UCHome上面的信息的读取显示。</li>
			<li>选择不同的基本模块，可以查看该基本模块下面的已有模块代码。</li>
			<li>您也可以通过创建模块操作，根据自己的需求，进行模块添加操作。</li>
			<li>只获取数据的模块只能进行模板内部调用，其他类模板代码可以进行两种模式的调用显示。
			<br><u>模板内部调用</u>:<br>
			此方式的调用代码可以放置于本系统内部模板的任意位置，但不能放置于其他系统的模板页面。采用批量缓存更新进制，效率高，服务器资源占有很少，速度快，推荐使用。</li>
			<br><u>JavaScript调用</u>:<br>
			此方式的调用代码可以放置于任何站点的任何页面，适用范围广。数据会自动缓存并按指定的时间间隔进行周期更新。</li>
			</ul>',
	'help_blocks_add' => '<ul>
			<li>通过创建不同的模块代码，并放置于模板中加以使用，就可以实现对论坛或UCHome上面的数据灵活显示。</li>
			<li>选择一个基本模块，在出现的创建模块向导页面中，根据站内对显示数据内容的需求进行自由设定，提交后就可以获得需要的模块代码了。</li>
			<li>选择模块风格为只获取数据时，模块将会把满足条件的数据读入到 <u><em>$_SBLOCK[变量名]</em></u> 数组中，您可以在模板文件对该数组变量进行自由操作，非常方便。</li>
			</ul>',
	'block_delete' => '删除',
	'block_blockname' => '模块名',
	'block_op' => '操作',
	'block_basic_type' => '基本模块',
	'block_code_1' => '模板内部调用代码',
	'block_code_2' => 'JavaScript调用代码',
	'block_cachetime_null' => '选择时间',
	'block_cachetime_900' => '15分钟',
	'block_cachetime_1800' => '30分钟',
	'block_cachetime_3600' => '1小时',
	'block_cachetime_7200' => '2小时',
	'block_cachetime_43200' => '12小时',
	'block_cachetime_86400' => '24小时',
	'block_title_cachetime' => '缓存更新时间间隔<p>单位:秒</p>',
	'block_title_cachename' => '变量名<p>您可以把获取的数据集合放置到一个模块变量中。在模板文件中可以使用 $_SBLOCK[变量名] 来调用该数据集合</p>',
	'block_title_skinid' => '选择模块风格文件<p>针对不同的模块，有不同的模块风格来控制该模块数据的显示样式。您可以通过 <a href="admincp.php?action=styles">模块风格</a> 功能，来为该模块添加、设置不同的风格</p>',
	'block_title_tplname' => '自己输入模块风格文件<p>如果上面列表中没有您需要的模块风格文件，您可以自己指定自己的模块风格文件地址。模块风格文件必须先上传，并放置于styles目录下面，后缀为.html.php</p>',
	'style_dir' => '目录名',
	'style_file' => '文件名',
	'block_model_1' => '向导模式',
	'block_model_2' => '高级模式',
	'block_name_length_error' => '您输入的模块名长度不符合要求，请检查确认',
	'online_documentation_new_modular_style' => '在线新建模块风格文件',

	//admin/admin_categories.php,
	'category_type' => '分类',
	'category_view_list' => '浏览分类',
	'category_add' => '添加分类',
	'category_title_name' => '分类名称',
	'category_html_path' => '分类存放HTML的路径<p>默认在根目录的news目录下，可在"系统配置"那设置生成的根目录</p>',
	'category_domain' => '二级域名绑定(以http://开头)<p>只在优化静态模式下有效</p>',
	'category_perpage' => '列表显示条数<p>列表页每页显示的条目数</p>',
	'category_prehtml' => '静态文件名前缀<p>只能由数字(0-9), 字母(a-z)和下划线(_)组成</p>',
	'category_displayorder' => '显示顺序',
	'space_op' => '操作',
	'category_add_sub' => '添加子分类',
	'merger_deletion' => '合并/删除',
	'category_edit_bbs' => '论坛读取设置',
	'category_delete' => '删除分类下资讯到垃圾箱',
	'category_root' => '根分类',
	'update_news_html' => '更新分类HTML',
	'html_path' => '静态页存放路径<p>在系统设置的资讯静态页存放路径下</p>',
	'per_makehtml' => '每次生成静态的条数',
	'pre_html' => '静态文件名前缀<p>只能由数字(0-9), 字母(a-z)和下划线(_)组成</p>',
	'per_makelisthtml' => '列表页显示的条数(第一页动态变化)',
	'help_categories_add' => '<ul>
			<li>跳转链接不为空的时候，访问该分类的时候，页面会跳转到指定的链接地址。</li>
			<li>通过<u>扩展读取分类设置</u>，您可以设置当前分类下面同时也读取其他分类(比如其子分类)的信息资源。默认只读取本分类自己的信息。</li>
			<li>您可以根据需要为当前分类指定单独一个模版风格文件。</li>
			</ul>',
	'help_categories_copy' => '<ul>
			<li>分类复制可将源分类的某些设置应用到其他多个分类，用于以一个分类的设置为基础，快速设置一批分类。</li>
			<li>分类复制一旦提交立即生效，并无法恢复，请仔细选择目标分类和设置项目。</li>
			</ul>',
	'category_source' => '源分类',
	'category_to' => '目标分类<p>选择要将源分类复制到哪些目标分类，可以按住 CTRL 多选</p>',
	'category_options_select' => '项目选择<p>选择要将源分类的哪些设置复制到目标分类，可按住 CTRL 多选</p>',
	'category_bbsmode_0' => '不读取论坛主题资源',
	'category_bbsmode_1' => '读取论坛主题资源',
	'help_categories_bbs' => '<ul>
			<li>您可以指定论坛中的满足一定条件的主题自动读取并归类于本分类下面，在门户页面上进行读取显示</li>
			<li>没有经过论坛推送到SupeSite操作的帖子，不会显示在门户页面上。</li>
			<li>您可以在<u>论坛版块</u>设置中，指定各个论坛版块的帖子推送模式(比如自动、手工、智能)。</li>
			</ul>',
	'move_cat' => '移动',
	'category_move_title' => '请选择移动目标分类<p>移动到某个分支下面</p>',

	//admin/admin_channel.php,
	'channel_add' => '创建频道',
	'help_channel' => '<ul>
			<li>系统内置了资讯频道。您可以为这些频道进行重新命名，并确定是否显示在站点菜单上面。</li>
			<li>如果您在站点<u>系统设置</u>里面未开启某个频道功能，则该频道不会显示在站点菜单上面。</li>
			<li>您也可以添加自己的频道，将某个频道设置为站点的首页，也可以指定频道访问地址为其他网站页面。</li>
			<li>自己添加的频道程序文件存放在 <u><em>channel</em></u> 文件夹下面，模板文件存放在 <u><em>templates</em></u> 对应的风格目录下面。您需要根据需求进行自我修改。</li>
			</ul>',
	'common_delete' => '删除',
	'channel_name' => '频道名',
	'channel_title_action' => '英文ID',
	'channel_title_action_add' => '英文ID(请不要包含下划线)',
	'channel_url' => '访问地址(为空为默认)',
	'channel_index' => '设为首页',
	'channel_show' => '启用频道',
	'channel_displayorder' => '顺序',
	'channel_tpl' => '模板名(为空为默认)',
	'channel_op' => '频道操作',
	'channel_tpl_edit' => '编辑模板',
	'channel_visit' => '访问频道',
	'channel_usesample_1' => '生成',
	'channel_usesample_0' => '不生成',
	'channel_all_index' => '综合首页',
	'channel_open' => '开放',
	'channel_close' => '关闭',
	'channel_hide' => '隐藏',
	'channel_category_1' => '科技世界',
	'channel_category_2' => '互联网络',
	'channel_category_3' => '财经报道',
	'channel_category_4' => '体育资讯',
	'channel_category_5' => '明星娱乐',
	'channel_category_6' => '生活资讯',
	'channel_category_7' => '网站建设',
	'channel_category_8' => '动态报道',
	'channel_category_9' => '特别关注',

	//admin/admin_check.php,
	'check_guest' => '游客',
	'check_grade_1' => '一等级',
	'check_grade_2' => '二等级',
	'check_grade_3' => '三等级',
	'check_grade_4' => '四等级',
	'check_grade_5' => '五等级',
	'check_no' => '普通信息',
	'check_yes' => '审核信息等级',
	'check_delete' => '垃圾信息',
	'help_check' => '<ul>
			<li>通过等级审核操作，您可以对信息进行等级分类处理、删除处理，从而可以有效的控制站点页面上信息的显示。</li>
			<li>用户发布的信息默认审核级别为待审状态。如果系统设置了信息需要审核，那么用户发布的信息必须经过审核才被聚合到站点上面。</li>
			<li>审核信息等级分为5个等级，您可以根据页面模板模块代码的获取条件，将信息灵活自由的进行等级分类。</li>
			<li>信息被放入垃圾箱后，信息将不再被读取显示。信息作者只有拥有重新发布被删信息的权限，才可以将删除的信息重新发布。</li>
			</ul>',
	'spacenews_title_subject' => '标题*',
	'spacenews_title_subject_note' => '当前可再写长度<strong id="maxlimit">80</strong>字节，最多80个字节',
	'check_username' => '发布者',
	'check_search' => '搜索',
	'check_explain' => '<ul style="line-height: 2em;list-style:none;margin:0;padding:0;"><li style="margin-bottom:0.5em;border-bottom:1px solid #CCC;">通过等级审核操作，审核管理人员可以对站内发布的信息进行等级分类处理、删除处理，从而可以有效的控制站点页面上信息的显示。</li><li style="margin-bottom:0.5em;border-bottom:1px solid #CCC;">审核信息等级分为5个等级，您可以根据页面聚合的条件，将信息自由进行等级分类。</li><li style="margin-bottom:0.5em;border-bottom:1px solid #CCC;">用户发布的信息默认审核级别为待审状态。管理员可以在站点设置中，设置是否允许待审状态的信息显示在站点聚合页面上。</li><li style="margin-bottom:0.5em;border-bottom:1px solid #CCC;">信息被放入垃圾箱后，用户将不能再编辑该信息。如果作者所在的用户组没有重新发布删除帖子的权限，那么垃圾箱里面的信息将不能被重新发布，只能选择删除。</li><li style="margin-bottom:0.5em;">由于系统拥有高速缓存和静态html机制，您的审核、删除操作，会在系统缓存、静态html下次更新后才会生效。如果您想立即生效，需要以管理员的身份到站点管理后台进行一次缓存清理，和html立即更新操作。</li>',
	'space_no_op' => '不操作',
	'check_op_check' => '审核信息等级',
	'space_delete_1' => '放入垃圾箱',
	'completely_erased' => '彻底删除',
	'check_op_movecat' => '重新归类',
	'space_batch_op' => '批量操作',
	'directly_delete' => '直接删除',
	'check_folder' => '重新发布',
	'general_state' => '普通状态',
	'space_select' => '选择',
	'check_type' => '系统',
	'check_catname' => '分类',
	'check_dateline' => '发布时间',
	'check_grade' => '级别',

	//admin/admin_comments.php,
	'comment_on_the_content' => '评论内容',
	'robot_robot_author' => '作者',

	//admin/admin_crons.php,
	'cron_title' => '计划任务',
	'help_crons' => '<ul>
			<li>通过计划任务可以使系统在规定时间自动执行某些特定任务的功能，在需要的情况下，您也可以方便的将其用于系统功能的扩展。</li>
			<li>计划任务是与系统核心紧密关联的功能特性，不当的设置可能造成系统功能的隐患，严重时可能导致系统无法正常运行，因此请务必仅在您对计划任务特性十分了解，并明确知道正在做什么、有什么样后果的时候才自行添加或修改任务项目。</li>
			<li>本功能中完全按照系统默认时差对时间进行设定和显示，而不会依据某一用户或管理员的时差设定而改变显示或设置的时间值。</li>
			</ul>',
	'cron_name' => '任务名',
	'cron_type' => '类型',
	'cron_available' => '状态',
	'cron_lastrun' => '上次执行',
	'cron_nextrun' => '下次执行',
	'cron_run' => '立即执行',
	'cron_available_1' => '正常',
	'cron_available_0' => '中止',
	'cron_weekday_0' => '星期日',
	'cron_weekday_1' => '星期一',
	'cron_weekday_2' => '星期二',
	'cron_weekday_3' => '星期三',
	'cron_weekday_4' => '星期四',
	'cron_weekday_5' => '星期五',
	'cron_weekday_6' => '星期六',

	//admin/admin_css.php,
	'css_view_list' => '浏览站点CSS',
	'css_add' => '添加站点CSS',
	'tpl_keyword_on_find' => '没有找到您要查找的字符',
	'tpl_title_keyword' => '查找字符',
	'css_help_tool' => 'CSS编辑助手',

	//admin/admin_customfields.php,
	'customfield_title' => '自定义信息',
	'customfield_view' => '浏览已有',
	'customfield_add' => '添加新配置',
	'help_customfields_list' => '<ul>
			<li>通过自定义信息，您可以实现在添加信息时为自己的信息填写更多属性，从而可以让信息共同拥有的某些属性以统一的样式展示给浏览者。</li>
			<li>通过<u>添加新配置</u>操作，您就可以进行信息个性字段的设置了。</li>
			</ul>',
	'customfield_title_delete' => '删除',
	'customfield_title_name' => '配置名称',
	'customfield_customfield' => '自定义字段',
	'customfield_title_isdefault' => '默认',
	'customfield_title_displayorder' => '显示顺序',
	'customfield_title_edit' => '编辑',
	'space_yes' => '是',
	'space_no' => '否',
	'customfield_input' => '文本框',
	'customfield_textarea' => '文本区域',
	'customfield_select' => '列表框',
	'customfield_check' => '复选框',
	'customfield_isdefault_0' => '不选中',
	'customfield_isdefault_1' => '默认选中',
	'customfield_customfield_title1' => '字段名',
	'customfield_customfield_title2' => '字段类型',
	'customfield_customfield_title3' => '列表选项',
	'customfield_addcustomfield' => '添加新字段',
	'help_customfields_add' => '<ul>
			<li>您可以通过点击<u>添加新字段</u>按钮，为该自定义信息设置多个不同的字段。</li>
			<li>每一个字段的类型，可以设置为单行的文本输入框、多行的文本区域、单选的列表框、多选的复选框等。</li>
			<li>当指定字段类型为列表框、复选框时，您需要在列表选项输入预先的选项，每行为一个选项。</li>
			</ul>',

	//admin/admin_database.php
	'common_continue' => '继续',
	'common_back' => '返回',
	'custom_database_about' => '根据需要自行选择需要备份的数据表',
	'database_date_unknown' => '未知',
	'database_export_custom' => '自定义备份',
	'database_export_supesite' => '完全备份',
	'database_export_dateline' => '时间',
	'database_export_del' => '删除',
	'database_export_extendins' => '使用扩展插入(Extended Insert)方式',
	'database_export_filename' => '备份文件名',
	'database_export_filesize' => '尺寸',
	'database_export_help' => '<ul>
				<li>数据备份功能根据您的选择，备份 SupeSite 的全部内容和设置数据。导出的数据文件可用"数据恢复"功能或 phpMyAdmin 导入。</li>
				<li>全部备份均不包含模板文件和附件文件。模板、附件和用户自定义头像的备份只需通过FTP等下载./templates、./attachments、./user目录即可，SupeSite 不提供单独备份。</li>
				<li>MySQL Dump 的速度比 SupeSite 分卷备份快很多，但需要服务器支持相关的 Shell 权限，同时由于 MySQL 本身的兼容性问题，通常进行备份和恢复的服务器应当具有相同或相近的版本号才能顺利进行。因此 MySQL Dump 是有风险的：一旦进行备份或恢复操作的服务器其中之一禁止了 Shell，或由于版本兼容性问题导致导入失败，您将无法使用 MySQL Dump 备份或由备份数据恢复；SupeSite 分卷备份没有此限制。</li>
				<li>数据备份选项中的设置，仅供高级用户的特殊用途使用，当您尚未对数据库做全面细致的了解之前，请使用默认参数备份，否则将导致备份数据错误等严重问题。</li>
				<li>十六进制方式可以保证备份数据的完整性，但是备份文件会占用更多的空间。</li>
				<li>压缩备份文件可以让您的备份文件占用更小的空间。</li>
				</ul>',
	'database_export_method' => '方式',
	'database_export_multivol' => 'SupeSite! 分卷备份 - 文件长度限制(kb)',
	'database_export_op' => '操作',
	'database_export_option' => '数据库备份选项',
	'database_export_options_charset' => '强制字符集',
	'database_export_options_sql_compatible' => '建表语句格式',
	'database_export_shell' => '系统 MySQL Dump (Shell) 备份',
	'database_export_type' => '类型',
	'database_export_usehex' => '十六进制方式',
	'database_export_usezip' => '压缩备份文件',
	'database_export_version' => '版本',
	'database_export_zip' => '压缩备份',
	'database_export_zip_0' => '不压缩',
	'database_export_zip_1' => '多分卷压缩成一个文件',
	'database_export_zip_2' => '每个分卷压缩成单独文件',
	'database_expot_volume' => '卷号',
	'database_import' => '数据恢复',
	'database_import_confirm' => '导入和当前 SupeSite 版本不一致的数据极有可能产生无法解决的故障，您确定继续吗？',
	'database_import_from' => '从服务器(填写文件名或URL):',
	'database_import_help' => '<ul><li>本功能在恢复备份数据的同时，将全部覆盖原有数据，请确定恢复前已将站点关闭，恢复全部完成后可以将站点重新开放。</li><li>数据恢复功能只能恢复由当前版本 SupeSite 导出的数据文件，其他软件导出格式可能无法识别。</li><li>备份数据只能使用从服务器恢复</li><li>如果您使用了分卷备份，只需手工导入文件卷 1，其他数据文件会由系统自动导入</li></ul>',
	'database_import_import' => '导入',
	'database_import_list' => '数据备份记录',
	'database_import_multivol_confirm' => '所有分卷文件解压缩完毕，您需要自动导入备份吗？导入后解压缩的文件将会被删除。',
	'database_import_multivol_prompt' => '分卷数据成功导入数据库，您需要自动导入本次其他的备份吗？',
	'database_import_multivol_unzip' => '备份文件解压缩完毕，您需要自动解压缩其他的分卷文件吗？',
	'database_import_success' => '数据成功导入 SupeSite 数据库。',
	'database_import_unzip' => '解压缩',
	'database_import_unzip_success' => '备份文件解压缩完毕，您需要自动导入备份吗？导入后解压缩的文件将会被删除。',
	'database_method' => '方式',
	'database_multivol' => '多卷',
	'database_op_export' => '数据库备份',
	'database_op_import' => '数据库恢复',
	'database_shell' => 'Shell',
	'database_export_type' => '类型',
	'supesite_all_database' => 'SupeSite 全部数据',
	'supesite_custom_database' => '自定义备份',
	'supesite_database' => 'SupeSite数据表',
	'supesite_more_select' => '更多选项',
	'database_export_multivol_redirect' => '分卷备份: 数据文件 #',
	'database_export_multivol_redirect1' => ' 成功创建，程序将自动继续。',
	'database_export_multivol_succeed' => '恭喜您，全部 ',
	'database_export_multivol_succeed1' => ' 个备份文件成功创建，备份完成。',
	'database_import_multivol_unzip_redirect' => '数据文件 # ',
	'database_import_multivol_unzip_redirect1' => ' 成功解压缩，程序将自动继续。',
	'database_import_multivol_redirect' => '数据文件 #',
	'database_import_multivol_redirect1' => '成功导入，程序将自动继续。',
	'effect_title_op' => '操作',
	'space_title_folder' => '文件夹',

	//admin/admin_friendlinks.php
	'xs_friendlinks' => '友情链接',
	'link_title_view' => '已有友情链接',
	'link_title_add' => '添加友情链接',
	'help_link_view' => '<ul>
			<li>您可以添加不同格式的友情链接，包括文字链接和图片链接等格式。</li>
			</ul>',
	'link_del' => '删除',
	'link_displayorder' => '显示顺序',
	'link_name' => '站点名称-说明',
	'link_url' => '站点URL',
	'link_logo' => 'Logo',
	'link_description' => '文字说明',
	'link_op'   => '操作',
	'link_name_about' => '站点名称<p>此处为文字显示，如果有Logo地址，则显示为图片友情链接</p>',
	'link_url_about' => '站点URL<p>友情链接地址(以http://开始)</p>',
	'link_logo_about' => 'Logo地址<p>如果填写此处，则显示图片友情链接(以http://开始或者相对路径)</p>',
	'link_displayorder_about' => '显示顺序<p>友情链接地址显示顺序</p>',
	'link_description_about' => '文字说明<p>(最大100字符)</p>',
	'block_xs_link_title_setid' => '指定站点友情链接id(s)',
	'block_xs_link_title_id' => '输入站点友情链接id(s)<p>多个用半角逗号,隔开</p>',

	//admin/admin_html.php,
	'html_title' => 'HTML操作',
	'userhtml_delete' => '文件删除',
	'userhtml_delete_success' => '删除完成',
	'userhtml_no_file' => '文件不存在',
	'userhtml_delete_fail' => '删除失败',
	'admincp_html_opening_note' => '<li>这里可以对站点页面是否启用html静态功能进行设置。</li>',
	'html_link_mode' => 'html链接模式',
	'html_link_mode_1' => '高效率模式:<br>页面的链接始终为PHP模式。在点击查看PHP模式的链接的时候，程序会自动跳转到已生成的静态页面。该模式效率高，页面执行时间短。',
	'html_link_mode_2' => '智能识别模式:<br>页面的链接会自动判断html文件存在，如果已经存在，则该页面在更新的时候，链接会变为静态html模式。该模式会影响页面执行时间，但对搜索收录效果较好。',
	'html_page_polymerization_installed_supesite' => 'SupeSite聚合页面html设置',
	'front_page_level' => '一级首页',
	'static_document_generated_html' => '生成html静态文件',
	'html_interval' => '每隔',
	'index_page_level2' => '二级列表页面',
	'see_page_level3' => '三级查看页面',
	'page_updated_minutes' => '分钟更新一次页面',
	'html_installed_using_the_system_recommended' => '使用系统推荐html配置覆盖当前配置',
	'save_setup_submit' => '保存设置',
	'update_html_note' => '<li>您可以指定一个html更新时间，所有的html文件在被点击查看的时候，都会强制更新到您指定的这个时间。</li>',
	'choose_a_time_update' => '选择一个更新时间',
	'time_set' => '设定时间',
	'delete_html_note' => '<li>输入你要删除的html文件名来删除指定的文件。</li>
		<li>您可以用 * 来代替任意的字符。比如，你要删除 n11.html n12.html 这样以 n1 开头的文件，你可以输入 n1*.html</li>
		<li>您可以用 | 来间隔不同的文件名。比如，您只想删除 n11.html n12.html 这两个文件，你可以输入  n11.html|n12.html</li>',
	'html_file_name_to_be_deleted_input' => '输入要删除的html文件名',
	'delete_file' => '删除文件',
	'delete_results' => '以下显示的是删除结果',
	'batch_last_several_file_generated_html_0' => '上次操作您要批量生成的html文件数',
	'batch_last_several_file_generated_html_1' => ' 个，操作时间',
	'batch_last_several_file_generated_html_2' => '您可以重新进行上次操作',
	'make_html_note' => '<li>本操作可以对html进行手工批量生成</li>
		<li>本操作将对您的服务器产生较大负载，建议在服务器清闲的时候进行。</li>
		<li>注意，如果您开启了html，指定的页面类型会在被浏览时，会自动生成html，因此，本操作不是生成html必需的操作</li>',
	'generation_page_types' => '生成页面类型',
	'view_page' => '查看页面',
	'page_list' => '列表页面',
	'channel_home_page' => '一级频道首页',
	'html_home_page' => '首页页面',
	'channel_type_choice' => '选择频道类型',
	'id_information_designated_areas' => '指定信息ID范围',
	'id_classification_system_set' => '设定系统分类ID',
	'whenever_the_number_of_pages' => '每次处理的页面个数',
	'id_classification_system_set_note' => '(多个ID之间用半角逗号","隔开)',
	'whenever_the_number_of_pages_note' => '(建议每次处理1个页面，否则可能因页面超时出现空白中止现象)',
	'date_format' => '格式',
	'ss_from_the_forum_to_html' => '同时对从论坛推送到SupeSite的帖子进行生成html操作(帖子的发布时间需要在指定的范围内)',
	'batch_create_html' => '批量生成',
	'generation_html_operation_completed' => '生成html操作全部完成，共处理页面个数:',
	'generation_html_end' => '生成html结束',
	'making_page_info_0' => '总共',
	'making_page_info_1' => '个页面，进入下一批(',
	'making_page_info_2' => ')生成html处理中，请等待......',
	'making_page_info_3' => '停止生成',

	//admin/admin_items.php,
	'check_grade_0' => '待审',
	'mass_transfer_classification' => '批量转移分类',
	'spaceblog_subject' => '标题',
	'information_operations_to_determine' => '确定对信息进行操作吗?',

	//admin/admin_polls.php,
	'poll_title' => '投票',
	'poll_select' => '选择',
	'poll_subject' => '投票主题',
	'poll_dateline' => '发布时间',
	'poll_updatetime' => '更新时间',
	'poll_op' => '操作',
	'poll_ismulti_0' => '单选',
	'poll_ismulti_1' => '多选',
	'poll_add_option' => '添加选项',
	'spacepolls_title_pollsurl' => '外部链接URL<p>如果填入外部链接，查看该投票时，将自动跳转到该链接。</p>',

	//admin/admin_prefields.php,
	'prefield_delete_success' => '成功删除',
	'prefield_newsauthor' => '原创作者',
	'prefield_newsfrom' => '信息来源',
	'prefield_title' => '预先值',
	'prefield_isdefault_0' => '否',
	'prefield_isdefault_1' => '是',
	'help_prefields' => '<ul>
			<li>您可以为站点发布信息时的系统内置字段进行预先选项设置。这些预先选项设置好后，用户在发布信息时，就可以从下拉列表中预先设置好的选项进行选择。</li>
			</ul>',
	'prefield_header_type' => '系统',
	'prefield_header_field' => '字段名',
	'prefield_header_value' => '可选值',
	'prefield_header_isdefault' => '默认',
	'prefield_header_op' => '操作',
	'prefield_edit' => '编辑',
	'prefield_delete' => '删除',

	//admin/admin_rightclick.php,
	'help_rightclick' => '<ul>
			<li>您可以为站点的书签系统生成右键功能文件。用户在下载并安装右键文件后，就可以更加方便的进行书签添加操作了。</li>
			</ul>',

	//admin/admin_robotmessages.php,
	'rototmessage_title' => '采集文章信息',
	'robotmessage_view_list_0' => '未导入文章',
	'robotmessage_view_list_1' => '已导入文章',
	'robotmessage_import' => '导入',
	'robotmessage_delete' => '删除',
	'robotmessage_import_delete_0' => '不删除',
	'robotmessage_import_delete_1' => '删除',
	'into_a_one_time' => '一次性全部导入',
	'only_selected_items' => '仅选中项',
	'robotmessage_select' => '选择',
	'robotmessage_subject' => '标题',
	'robotmessage_catid' => '分类',
	'robotmessage_robotid' => '采集机器人',
	'robotmessage_robottime' => '采集时间',
	'robotmessage_author' => '作者',
	'into_a_one_off' => '一次性导入',

	//admin/admin_robots.php,
	'robot_title' => '采集器',
	'robot_defaultdateline_delete' => '清空',
	'robot_view_list' => '浏览机器人',
	'robot_add' => '添加新机器人',
	'robot_robot_import' => '导入机器人',
	'robot_progress' => '采集过程',
	'robot_progress_stop' => '中止采集',
	'robot_robot_start' => '采集机器人开始工作',
	'robot_robot_deal' => '处理',
	'robot_robot_list' => '索引列表页面',
	'robot_robot_begin' => '开始',
	'robot_robot_end' => '结束',
	'robot_robot_text' => '内容',
	'robot_robot_url' => '链接',
	'robot_robot_area' => '区域',
	'robot_robot_success' => '完成',
	'robot_robot_next_list' => '当前索引页面文章采集完毕，进入下一个索引页面',
	'robot_progress_next_list' => '正在采集下一个文章列表...',
	'robot_robot_message_page' => '文章分页页面',
	'robot_robot_message' => '内容',
	'robot_robot_all_max' => '采集文章总数目已经达到最大限制',
	'robot_robot_failed' => '失败',
	'robot_robot_next_message' => '单次采集数目达到最大限制，进入下一个采集操作',
	'robot_robot_url_error' => '无法链接到指定的URL地址',
	'robot_robot_result' => '采集完成，点击此处查看采集结果',
	'exportmessage_begin' => '开始将数据写入文件',
	'exportmessage_success' => '成功写入文件',
	'exportmessage_end' => '结束将数据写入文件',
	'exportmessage_download' => '点击鼠标右键，选择目标另存为，下载到本地',
	'robot_robot_name' => '采集名',
	'robot_robot_robot_time' => '采集时间',
	'robot_robot_num' => '采集次数',
	'robot_robot_op_select' => '选择操作',
	'robot_robot_op_start' => '开始采集',
	'robot_robot_op_edit' => '编辑配置',
	'robot_robot_op_copy' => '复制配置',
	'robot_robot_op_export' => '导出配置',
	'robot_robot_op_result' => '查看结果',
	'robot_robot_op_export_message' => '导出文章',
	'robot_robot_op_clear' => '清空文章',
	'robot_robot_op_delete' => '删除机器',
	'robot_listurltype_manual' => '手工输入',
	'robot_listurltype_auto' => '自动增长',
	'robot_savepic_0' => '否',
	'robot_savepic_1' => '是',
	'robot_saveflash_0' => '否',
	'robot_saveflash_1' => '是',
	'robot_messagepagetype_page' => '页码导航',
	'robot_messagepagetype_next' => '上下页导航',
	'robot_subjectallowrepeat_1' => '允许重复',
	'robot_subjectallowrepeat_0' => '不允许重复',
	'robot_subjectreplace' => '替换前的字符',
	'robot_subjectreplace_exp' => '(多个关键字用 | 隔开，用*代替任意符号。多条替换规则请点击"添加"按钮来创建多条替换规则)',
	'robot_subjectreplaceto' => '替换后的字符',
	'robot_subjectreplaceto_exp' => '可以用[string]来表示替换前的字符',
	'robot_messagereplace' => '替换前的字符',
	'robot_import_ignoreversion_0' => '否',
	'robot_import_ignoreversion_1' => '是',
	'common_submit_import' => '导入配置',
	'robot_robot_subject_no_key' => '标题不包含关键字，跳过',
	'robot_robot_subject_key_cancel' => '标题包含关键字，跳过',
	'robot_robot_subject_null' => '标题经处理后为空，跳过',
	'robot_robot_subject_exists' => '文章已经存在，跳过',
	'robot_robot_message_no_key' => '内容不包含关键字，跳过',
	'robot_robot_message_key_cancel' => '内容包含关键字，跳过',
	'robot_robot_subject' => '标题',
	
	'robot_robot_itemfrom' => '文章来源',
	'robot_robot_picarr' => '图片链接',
	'robot_robot_flasharr' => 'FLASH链接',
	'robot_robot_pagearr' => '分页链接',
	'robot_robot_cache_read' => '列表缓存文件成功读取',
	'robot_robot_cache_write_failed' => '列表缓存文件无法写入',
	'robot_robot_cache_write_success' => '列表缓存文件成功写入',
	'intelligent_config' => '智能采集型',
	'robot_debug_no_process' => '未指定进程',
	'robot_debug_no_link' => '无链接',
	'robot_debug_link_list' => '链接列表',
	'robot_debug_excessive_list' => '由于链接列表大于1000条,程序调试程序只显示头1000条数据.',
	'robot_debug_connecting_success' => '连接成功',
	'robot_debug_unable_to_connect' => '无法连接',
	'robot_debug_unable_to_read' => '无法读取',
	'robot_debug_pages_encode' => '被采集页面的编码',
	'robot_debug_no_recognition' => '没有识别出页面编码,请进行人工识别.',
	'robot_debug_encode_the_same' => '如果两个编码相同无需进行设置',
	'robot_debug_web_site_encode' => '您的网站编码为:',
	'robot_debug_encode_not_set' => '采集页面编码未设置,系统不进行转码工作.如果调试区域为乱码时,请您设置"采集页面编码".',
	'robot_debug_regional_list_not_set' => '列表区域识别规则未设置,程序将自动识别"列表区域",此种方法会产生一定误差.',
	'robot_debug_regional_list_not_set_2' => '没识别出任何内容,请检查"列表区域识别规则"',
	'robot_debug_subject_url_not_set' => '文章链接URL识别规则未设置,程序将自动识别"列表区域"所有链接,此种方法会产生一定误差.',
	'robot_debug_subject_url_not_set_2' => '文章链接URL识别规则未设置,程序将自动识别"列表区域"所有链接,此种方法会产生一定误差.',
	'robot_debug_subject_url_cancel_0' => '文章链接URL剔除"前"为',
	'robot_debug_subject_url_cancel_1' => '文章链接URL剔除"后"链接为',
	'robot_debug_regular' => '正则表达式',
	'robot_debug_url_cancel_no_link' => '文章链接URL剔除后没链接',
	'robot_debug_subject_url_filter_0' => '文章链接URL过滤"前"为',
	'robot_debug_subject_url_filter_1' => '文章链接URL过滤"后"链接为',
	'robot_debug_subject_url_filter_no_link' => '文章链接URL过滤后没链接',
	'robot_debug_subjecturllinkpre_0' => '文章链接URL补充前缀"前"为',
	'robot_debug_subjecturllinkpre_1' => '文章链接URL补充前缀"后"链接为',
	'robot_debug_subjecturllinkpf_0' => '文章链接URL补充后缀"前"为',
	'robot_debug_subjecturllinkpf_1' => '文章链接URL补充后缀"后"链接为',
	'robot_debug_subjectrule_no_set_0' => '文章标题识别规则未设置',
	'robot_debug_subjectrule_no_set_1' => '没识别出任何内容,请检查"文章标题识别规则"',
	'robot_debug_subjectfilter_0' => '文章标题过滤后为',
	'robot_debug_subjectfilter_1' => '文章标题过滤后没有内容',
	'robot_debug_subjectreplace_0' => '文章标题文字替换"前"为',
	'robot_debug_subjectreplace_1' => '文章标题文字替换"后"为',
	'robot_debug_subject' => '文章标题',
	'robot_debug_subjectkey_0' => '文章标题不包含指定关键词,不会被采集.',
	'robot_debug_subjectkey_1' => '文章标题包含指定关键词,将被采集.',
	'robot_debug_subjectkeycancel_0' => '文章标题不包含指定关键词,将被采集.',
	'robot_debug_subjectkeycancel_1' => '文章标题包含指定关键词,不会被采集.',
	'robot_debug_messagerule_0' => '文章内容识别规则未设置,程序将自动识别"文章内容",此种方法会产生一定误差.',
	'robot_debug_messagerule_1' => '没识别出任何文章内容,请检查"文章内容识别规则"',
	'robot_debug_messagefilter_0' => '文章内容过滤"前"为',
	'robot_debug_messagefilter_1' => '文章内容过滤"后"为',
	'robot_debug_messagefilter_2' => '文章内容过滤后没有内容.',
	'robot_debug_messagereplace_0' => '文章内容文字替换"前"为',
	'robot_debug_messagereplace_1' => '文章内容文字替换"后"为',
	'robot_debug_message' => '文章内容',
	'robot_debug_messagekey_0' => '文章内容不包含指定关键词,不会被采集.',
	'robot_debug_messagekey_1' => '文章内容包含指定关键词,将被采集.',
	'robot_debug_messagekeycancel_0' => '文章内容不包含指定关键词,将被采集.',
	'robot_debug_messagekeycancel_1' => '文章内容包含指定关键词,不会被采集.',
	'robot_debug_messageformat_0' => '文章内容格式化前为',
	'robot_debug_messageformat_1' => '文章内容格式化后为',
	'robot_debug_messagepageurllinkpre_0' => '文章内容分页链接URL补充前缀"前"为',
	'robot_debug_messagepageurllinkpre_1' => '文章内容分页链接URL补充前缀"后"链接为',
	'robot_debug_messagepageurllinkpf_0' => '文章内容分页链接URL补充后缀"前"为',
	'robot_debug_messagepageurllinkpf_1' => '文章内容分页链接URL补充后缀"后"链接为',
	'robot_debug_fromrule_0' => '信息来源识别规则未设置',
	'robot_debug_fromrule_1' => '信息来源固定值',
	'robot_debug_authorrule_0' => '作者识别规则未设置',
	'robot_debug_authorrule_1' => '作者固定值',
	'robot_debug_uidrule_0' => '发布者UID未设置',
	'robot_debug_uidrule_1' => '发布者UID随机抽取值',
	'robot_delete' => '删除',
	'robot_debugframe' => '调试窗口<p>Debug URL: <br />(例如:http://www.xxx.com/abc.htm)',
	'robot_allowurlnull_0' => '每次调试清空Debug URL',
	'robot_allowurlnull_1' => '清空URL',
	'robot_debugframe_info' => 'Debug URL作用: 不受采集链接的影响,方便采集规则的调试.<br />Debug URL不清空带来的麻烦: 因为不同的测试针对的网址会略有不同,当URL框中有值时程序会跳过正常的URL.</p>',
	'robot_debugframe_close' => '关闭',
	'robot_debug' => '测试',
	'robot_debug_auto_recognition' => '自动识别',
	'robot_debug_add' => '添加',
	'robot_debug_showlisturl' => '测试:显示链接',
	'robot_debug_pinglisturl' => '测试:尝试连接',
	'robot_debug_auxiliary' => '程序辅助识别',
	'robot_debug_auto_subjecturlrule' => '("列表区域识别规则"为空时，程序自动识别"列表区域")',
	'robot_debug_auto_subjecturllinkrule' => '("文章链接URL识别规则"为空时，程序自动识别"列表区域"所有链接)',
	'robot_debug_auto_subjecturllinkpre' => '("文章链接URL补充前缀"为空时，程序自动补充前缀)',
	'robot_debug_auto_messagerule' => '("文章内容识别规则"为空时，程序自动识别"文章内容")',
	'robot_debug_auto_messagepageurllinkpre' => '("文章内容分页链接URL补充前缀"为空时，程序自动补充前缀)',
	'robot_debug_auto_picurllinkpre' => '("图片/FLASH链接的URL补充前缀"为空时，程序自动补充前缀)',
	'robot_debug_info_subjecturllinkcancel' => '文章链接URL剔除规则<p>功能:凡符合规则的链接不进行采集,区分大小写.用 * 来代替任意字符、换行、回车</p><p>多个规则之间用 | 隔开</p>',
	'robot_debug_info_subjecturllinkfilter' => '文章链接URL过滤规则<p>功能:过滤掉链接中的字符串,可以用来整理链接,区分大小写.用 * 来代替任意字符、换行、回车</p><p>多个规则之间用 | 隔开</p>',
	'robot_subjecturllinkpf' => '文章链接URL补充后缀',
	'robot_messageformat' => '文章内容格式化<p>此操作将去除网页多余代码,并将文章内容按原有段落分段.格式化的过程为程序自动分析,会存在一些误差.</p>',
	'robot_messageformat_1' => '格式化',
	'robot_messageformat_0' => '不格式化',
	'robot_messagepageurllinkpf' => '文章内容分页链接URL补充后缀',
	'robot_fromrule_info' => '当规则中不出现"标记符([from])"时,此值为"固定值"',
	'robot_authorrule_info' => '当规则中不出现"标记符([author])"时,此值为"固定值"',
	'robot_uidrule' => '发布者UID<p>可以指定多个发布者UID,采集结果在入库时随机抽取其中的一个,UID必须是网站的真实用户UID.多个发布者UID之间用 | 隔开</p>',
	'robot_debug_regional_source' => '识别后有内容,区域源码',
	'robot_debug_not_content' => '没识别出任何内容,请检查识别规则',
	'robot_debug_url' => '测试网页地址',
	'robot_debug_source_code' => '网页源码',
	'robot_reverseorder' => '文章倒序采集<p>设为此项后列表中的文章将从最后面的开始采集</p>',

	//admin/admin_settings.php,
	'setting_title' => '系统设置',
	'setting_pconnect_0' => '否',
	'setting_pconnect_1' => '是',
	'setting_dbreport_0' => '不报告',
	'setting_dbreport_1' => '报告',
	'setting_gzipcompress_0' => '不启用GZIP压缩',
	'setting_gzipcompress_1' => '启用GZIP压缩',
	'setting_urltype_1' => '简短通用模式(URL较短但影响页面效率)',
	'setting_urltype_4' => '高效通用模式(页面效率高但URL较长)',
	'setting_urltype_2' => '简短APACHE模式(仅Apace服务器适用)',
	'setting_urltype_5' => '高效APACHE模式(仅Apace服务器适用)',
	'setting_urltype_3' => '简短REWRITE模式(需服务器REWRITE支持)',
	'setting_bbsurltype_site' => '站点模式',
	'setting_bbsurltype_bbs' => '链接到应用',
	'setting_htmltime_5minute' => '5分钟',
	'setting_htmltime_10minute' => '10分钟',
	'setting_htmltime_15minute' => '15分钟',
	'setting_htmltime_20minute' => '20分钟',
	'setting_htmltime_25minute' => '25分钟',
	'setting_htmltime_30minute' => '30分钟',
	'setting_htmltime_1hour' => '1小时',
	'setting_htmltime_2hour' => '2小时',
	'setting_htmltime_3hour' => '3小时',
	'setting_htmltime_4hour' => '4小时',
	'setting_htmltime_5hour' => '5小时',
	'setting_htmltime_6hour' => '6小时',
	'setting_htmltime_12hour' => '12小时',
	'setting_htmltime_1day' => '1天',
	'setting_htmltime_2day' => '2天',
	'setting_htmltime_3day' => '3天',
	'setting_htmltime_1week' => '1周',
	'setting_htmltime_2week' => '2周',
	'setting_htmltime_3week' => '3周',
	'setting_htmltime_1month' => '1个月',
	'setting_htmltime_6month' => '6个月',
	'setting_htmltime_1year' => '1年',
	'setting_attachmentdirtype_all' => '不归类',
	'setting_attachmentdirtype_year' => '按年归类',
	'setting_attachmentdirtype_month' => '按月归类',
	'setting_attachmentdirtype_day' => '按天归类',
	'setting_attachmentdirtype_md5' => '随机归类',
	'setting_debug_0' => '不显示',
	'setting_debug_1' => '显示',
	'setting_watermark_0' => '不添加水印',
	'setting_watermark_1' => '添加水印',
	'setting_thumboption_4' => '综合最佳缩放',
	'setting_thumboption_8' => '宽度最佳缩放',
	'setting_thumboption_16' => '高度最佳缩放',
	'setting_thumbcutmode_0' => '默认模式',
	'setting_thumbcutmode_1' => '左或上剪切模式',
	'setting_thumbcutmode_2' => '中间剪切模式',
	'setting_thumbcutmode_3' => '右或下剪切模式',
	'setting_allowguest_0' => '不开放',
	'setting_allowguest_1' => '开放',
	'setting_allowcache_0' => '不开启缓存',
	'setting_allowcache_1' => '开启缓存',
	'setting_allowtagshow_0' => '不启用',
	'setting_allowtagshow_1' => '启用',
	'setting_needcheck_0' => '不启用',
	'setting_needcheck_1' => '启用',
	'setting_imagemode_item' => '主题单图片展示模式',
	'setting_imagemode_image' => '图片全展示模式',
	'setting_news_html_path' => '设置资讯生成的HTML的存放地址',
	'help_settings' => '<ul>
			<li>您通过本页面可以对站点基本信息、附件目录、html目录、图片水印、图片缩略图等进行参数设定。</li>
			</ul>',
	'thumbnail_specifications_news' => '资讯缩略图规格<p>默认规格400x300</p>',
	'width' => '宽度',
	'height' => '高度',
	'pixel' => '像素',
	'setting_allowfeed' => '是否开启事件推送功能',
	'setting_customaddfeed' => '加入事件设置',
	'setting_customaddfeed_1' => '主题',
	'setting_customaddfeed_2' => '回复',
	'functional_verification_codes_prohibit' => '是否禁止验证码功能',
	'verification_codes_0' => '禁止使用',
	'verification_codes_1' => '使用验证码',
	'comments_and_the_number_of_shows' => '评论显示的数目',
	'do_not_open' => '不开启',
	'mail_set' => '邮件设置',
	'mail_send_mode' => '邮件发送方式',
	'mail_mode_php_sendmail' => '通过 PHP 函数的 sendmail 发送(推荐此方式)',
	'mail_send_socket_esmtp' => '通过 SOCKET 连接 SMTP 服务器发送(支持 ESMTP 验证)',
	'mail_mode_php_smtp' =>'通过 PHP 函数 SMTP 发送 Email(仅 Windows 主机下有效, 不支持 ESMTP 验证)',
	'mail_header_sign' => '邮件头的分隔符',
	'mail_header_lf' => '使用 LF 作为分隔符(通常为 Unix/Linux 主机)',
	'mail_header_crlf' => '使用 CRLF 作为分隔符(通常为 Windows 主机)',
	'mail_header_cr' => '使用 CR 作为分隔符(通常为 Mac 主机)',
	'accept_username' => '收件人显示用户名',
	'smtp_server' => 'SMTP 服务器',
	'smtp_port' => 'SMTP 端口',
	'smtp_default_port' => ' 默认为 25',
	'require_validate' => '要求身份验证',
	'send_mail_email' => '发信人邮件地址',
	'email_format' => '格式为"username &lt;user@domain.com&gt;"，也可以只填地址',
	'smtp_user' => 'SMTP 用户名',
	'smtp_password' => 'SMTP 密码',
	'allowpostnews' => '是否允许推送信息<p>关闭推送将关闭全站的推送功能</p>',
	'postnews_on' => '开启',
	'postnews_off' => '不开启',

	//admin/admin_sitemap.php,
	'sitemap_help' => '<ul><li>你可以使用本工具来为您站点上面的公开信息创建sitemap文件。Sitemap文件使用XML格式来记录您的整个网站的公开信息链接和最后更新时间</li><li>您目前可以创建生成baidu和google两种收录格式的sitemap</li><li>在生成Sitemap之前，请仔细阅读<a href="http://news.baidu.com/newsop.html" target="_blank">互联网新闻开放协议</a>和<a href="https://www.google.com/webmasters/tools/docs/en/protocol.html" target="_blank">Google Sitemap协议</a></ul>',
	'sitemap_info' => '生成完成,查看生成的',
	'sitemap_info_0' => '提交',
	'generation_sitemap_clicking_here' => '点击此处生成sitemap',
	'sitemap_name' => 'sitemap名称',
	'sitemap_type' => 'sitemap类型',
	'sitemap_num' => 'sitemap网址数',
	'sitemap_createtime' => '最后生成时间',
	'sitemap_createtype' => '生成方式',
	'sitemap_createtype_0' => '重新生成',
	'sitemap_createtype_1' => '累加生成',
	'sitemap_lastitemid' => '最后更新itemid',
	'sitemap_changefreq' => '更新周期<p>baidu的周期单位为:分钟</p>',
	'sitemap_config_view' => '浏览sitemap配置',
	'sitemap_config_add' => '添加sitemap配置',
	'sitemap_start_create'=> '请稍候,程序正在生成itemid从',
	'sitemap_start_create_1'=>'的记录',

	//admin/admin_spacecache.php,
	'spacecache_title' => '缓存管理',
	'spacecache_op' => '操作',
	'spacecache_cachekind_cache' => '站点',
	'spacecache_cachekind_tagcache' => 'TAG概览',
	'spacecache_filekind_js' => 'JavaScript调用缓存',
	'spacecache_filekind_robot' => '采集临时数据缓存',
	'spacecache_filekind_tpl' => '模板编译文件',
	'spacecache_filekind_ad' => '广告缓存',
	'spacecache_filekind_announcement' => '公告缓存',
	'spacecache_filekind_category' => '分类缓存',
	'spacecache_filekind_censor' => '词语屏蔽缓存',
	'spacecache_filekind_config' => '配置缓存',
	'spacecache_filekind_crons' => '计划任务缓存',
	'spacecache_filekind_group' => '用户组缓存',
	'spacecache_filekind_bbs_settings' => '论坛设置缓存',
	'spacecache_filekind_bbs_bbcodes' => '论坛BBCODE缓存',
	'spacecache_filekind_bbs_style' => '论坛风格缓存',
	'help_cache' => '<ul>
			<li>SupeSite系统使用特有的数据缓存机制，来加快站点速度，降低数据库负载。</li>
			<li>清空缓存后，系统会自动进行缓存重建工作，负载会在一个短时间内增加，因此请不要经常进行本操作。</li>
			<li>开启缓存功能后，站点数据会在一定时间间隔进行自动更新。在缓存未自动更新前，站点显示的数据是以前的数据，因此站点显示存在一点延迟。但综合来讲，开启缓存还是非常有必要的。</li>
			</ul>',
	'spacecache_model' => '模型缓存',

	//admin/admin_spacenews.php,
	'spacenews_newspage' => '资讯页面',
	'spacenews_typepage' => '分类页面',
	'spacenews_title_message_page_none' => '当前资讯只有一个分页',
	'spacenews_title' => '资讯',
	'spacenews_view_list' => '浏览资讯',
	'space_all_catid' => '所有分类',
	'space_all_digest' => '不限制精华',
	'space_digest_1' => '精华I',
	'space_digest_2' => '精华II',
	'space_digest_3' => '精华III',
	'space_order_default' => '默认排序',
	'space_order_lastpost' => '最后回复',
	'space_order_uid' => '作者',
	'space_order_viewnum' => '查看数',
	'space_order_replynum' => '回复数',
	'space_sc_asc' => '升序',
	'space_sc_desc' => '降序',
	'space_perpage_loop_1' => '每页',
	'space_perpage_loop_2' => '条',
	'space_folder_2' => '草稿箱',
	'space_folder_4' => '待审箱',
	'space_folder_1' => '发布箱',
	'space_folder_3' => '垃圾箱',
	'update_html' => '更新生成静态页',
	'update_html_set' => '文章静态化设置',
	'space_select_filter' => '查看',
	'space_order_filter' => '排序',
	'space_move_folder' => '移动文件夹',
	'admin_func_move_folder' => '审批信息',
	'grades_audit' => '等级审核',
	'space_move_cat' => '移动分类',
	'space_digest' => '精华',
	'space_top' => '置顶',
	'space_allowreply' => '评论',
	'space_digest_0' => '非精华',
	'space_top_0' => '非置顶',
	'space_top_1' => '置顶I',
	'space_top_2' => '置顶II',
	'space_top_3' => '置顶III',
	'space_delete_0' => '直接删除',
	'space_allowreply_1' => '允许评论',
	'space_allowreply_0' => '不允许评论',
	'spaceblog_title_catid' => '系统分类',
	'spacenews_title_author' => '添加人',
	'space_dateline' => '发布日期',
	'search_not_info' => '没有符合条件的信息',
	'audit_level' => '审核级别',
	'spaceblog_viewpage_success' => '完成，点击链接可以查看该页面。',
	'spacenews_op_add' => '继续发布新资讯',
	'spacenews_title_message_op_add' => '添加新分页',
	'continue_the_current_editorial_page' => '继续编辑当前页',
	'common_continue_list_edit' => '进行列表管理',
	'space_customfield_none' => '不使用',
	'space_title_customfield' => '自定义信息<p>使用本功能，您可以为该条信息添加更多个性字段内容。点击此处可以<a href=spacecp.php?action=customfields&type=$type><u>管理</u></a>自定义信息</p>',
	'spacenews_title_message_op_delete' => '删除当前分页',
	'spacenews_needcheck' => '您目前发布的资讯需要经过审阅之后才能公开发布。<br>在没有通过审阅之前，您发布的资讯将自动放置在待审箱中。',
	'spacenews_page_need_submit' => '您可以通过"编辑区"中的"插入分页标志"(如图所示<img src="admin/images/branch.jpg">)按钮实现分页。',
	'spacenews_dateline' => '资讯发布日期<p>您可以自己指定当前资讯的发布日期。注意，不能是当前时间以后的日期。</p>',
	'extract_content' => '获取远程资讯<p>填入网址，点击"获取远程资讯"按钮就可获得网址中的资讯信息</p>',
	'simple_extraction' => '简单获取',
	'smart_extraction' => '智能获取',
	'extract_the_contents_of_the_current_location_url' => '获取远程资讯',
	'automatic_analysis_of_coding' => '自动分析编码',
	'titlestyle' => '标题样式',
	'titlestylecolor' => '文字颜色',
	'titlestylesize' => '文字大小',
	'watermark_article' => '是否开启资讯干扰码',
	'show_linknum' => '首页显示友情链接数',
	'commenttime_help' => '评论间隔时间<p>(为0时无间隔限制,单位:秒)</p>',
	'not_to_create_watermark' => '禁止干扰码',
	'create_watermark' => '开启干扰码',
	'not_view_update' => '不防刷新',
	'view_update' => '防刷新',
	'setting_title_updateview' => '是否开启防刷新<p>注意:不开启防刷新会增加服务器负担</p>',
	'delete_all_note' => '注意：本操作不能恢复，一旦删除后，数据将丢失，请谨慎操作！',
	'delete_all_message_0' => '共',
	'delete_all_message_1' => '记录,剩余',
	'delete_all_message_3' => '未删除,垃圾箱数据正在删除中',
	'get_ralatekw' => '可用TAG',
	'spacenews_info_null' => '您目前发布的资讯需要经过审阅之后才能公开发布。在没有通过审阅之前，您发布的资讯将自动放置在待审箱中。',

	//admin/admin_spaces.php,
	'spaces_username' => '用户名',
	'space_submit_filter' => '浏览',
	'spaces_spacecp' => '信息管理',
	
	//admin/admin_styles.php,
	'style_title' => '模块风格',
	'style_view_list' => '浏览风格',
	'style_add' => '添加新风格',
	'help_styles' => '<ul>
			<li>针对不同的模块系统，您可以通过模块风格功能，预先为该模块设置数据显示的样式风格文件。这些小的风格文件控制了通过模块代码获得的数据是以什么样的版式进行展示。</li>
			<li>样式风格文件存放在 <u><em>styles</em></u> 目录下面，以 <u><em>.html.php</em></u> 文件结尾。</li>
			</ul>',
	'style_title_tplname' => '风格方案名',
	'style_title_tpltype' => '归属系统',
	'style_title_tplfilepath' => '模板文件地址',
	'style_title_op' => '操作',
	'style_select_file' => '选择一个存在的风格文件',

	//admin/admin_styletpl.php,
	'module_style_paper' => '模块风格文件',
	'browse_documents_style' => '浏览风格文件',
	'add_style_paper' => '添加风格文件',
	'tpl_title_preview' => '预览',

	//admin/admin_tags.php,
	'tag_view_list' => '浏览TAG',
	'tag_search_tagname' => 'TAG名',
	'tag_search_tagid' => 'TAG ID',
	'tag_search_username' => '创建者名',
	'tag_search_uid' => '创建者UID',
	'tag_close_0' => '正常',
	'tag_close_1' => '锁定',
	'tag_order_dateline' => '创建时间',
	'tag_order_uid' => '创建者',
	'tag_order_spacenewsnum' => '资讯数',
	'help_tag' => '<ul>
			<li>您可以对站内TAG进行锁定、合并、改名、与其他TAG进行关联等操作。</li>
			<li>如果您将锁定了一个TAG，则该TAG的统计数据将被清空，所有带有该TAG的信息将不能被发布。</li>
			</ul>',
	'tag_search' => '搜索',
	'tag_close' => '状态',
	'tag_order' => '排序',
	'tag_view_submit' => '浏览',
	'tag_op_close' => '锁定',
	'tag_op_merge' => '合并',
	'tag_tagname' => 'TAG名',
	'tag_relativetags' => '相关TAG',
	'tag_creat_dateline' => '创建时间',
	'tag_username' => '创建者',
	'tag_spacenewsnum' => '资讯数',
	'tag_op' => '操作',
	'topic_reselect_template' => '重新选择模板',

	//admin/admin_tpl.php,
	'tpl_view_list' => '浏览站点模板',
	'tpl_add' => '添加站点模板',

	//admin/admin_userprofile.php,
	'userprofile_bitian' => '必填',
	'block_link_order_displayorder' => '显示顺序',

	//admin/admin_words.php,
	'supe_words_censor' => '词语过滤',
	'words_censor_help' => '<ul><li>替换前的内容可以使用限定符 {x} 以限定相邻两字符间可忽略的文字，x 是忽略字符的个数。如 "a{1}s{2}s"(不含引号) 可以过滤 "ass" 也可过滤 "axsxs" 和 "axsxxs" 等等。</li><li><strong>一个中文占用两个字符</strong></li><li>为不影响程序效率，请不要设置过多不需要的过滤内容。</li><li>为了过滤的准确性，过滤词不能少于两个字</li></ul>',
	'words_del' => '删除',
	'bad_words' => '不良词语',
	'replace_words' => '替换为',
	'words_op_user' => '操作者',
	'words_export' => '导出词表',
	'words_add' => '新增',
	'words_add_lot' => '批量增加',
	'words_addcensor_help' => '<ul><strong>添加格式</strong><li>每行一组过滤词语。</li><li>不良词语和替换词语之间使用"="进行分割。</li><li>如果只是想将某个词语直接替换成 **，则只输入词语即可。</li></ul>',
	'words_addcensor_all' => '清空当前词表后导入新词语，此操作不可恢复，建议首先 <a href="admincp.php?action=words&op=export">导出词表</a> , 做好备份。',
	'words_addcensor_over' => '使用新的设置覆盖已经存在的词语',
	'words_addcensor_add' => '不导入已经存在的词语',
	'words_addcensor_example' => '例如：',
	'censor_keywords_exists' => '关键词已经存在',

	//admin/admin_model.php
	'model_index' => '模型首页',
	'click_to_enter' => '点击可进入',
	'field' => '字段',
	'model_show' => '显示',
	'success' => '成功',
	'create_model_suc' => '模型建立成功',
	'create_model_help_1' => '第一步完成.模型初步建立成功，您可以通过"模型首页"链接查看新建的模型，但建立模型只是刚刚开始.',
	'create_model_help_2' => '第二步',
	'create_model_help_2_about' => '新建立的模型没有任何字段，更不具有信息，它就像是一个平台等待着您的搭建.',
	'create_model_help_3' => '第三步',
	'create_model_help_3_1' => '当模型自定义字段添加完成后，模型框架基本已经搭建完成.',
	'create_model_help_3_2' => '每个模型有自己的独立分类，您可通过',
	'create_model_help_3_3' => '进行设置',
	'create_model_help_4' => '第四步 "发布信息"',
	'new_create_field' => '新建字段',
	'field_management' => '字段管理',
	'edit_model_suc' => '模型修改成功',
	'return_model_category' => '返回模型列表',
	'go_field_management' => '进入字段管理',
	'go_info_management'=> '进入信息管理',
	'fieldtype_length_1' => '当数据表字段类型为',
	'fieldtype_length_2' => '时，字段长度不能大于255',
	'the_fieldtype_1' => '当数据表字段类型为',
	'the_fieldtype_2'=> '时，字段长度不能小于等于0',
	'the_fieldtype_3' => '时，初始化值只能为整型数字型.',
	'the_fieldtype_4' => '时，初始化值只能为数字型.',
	'system_field' => '系统字段',
	'field_copy' => '复制',
	'you_can' => '您可以通过',
	'in_new_customfield' => '在新模型中自定义字段',
	'aslo_through' => '也可以通过',
	'in_new_customfield_1' => '对自定义字段维护',
	'model_del_suc' => '模型删除成功',
	'the_following_documents' => '以下文件',
	'view_field' => '浏览字段',
	'export_model' => '导出模型',
	'delete_model' => '删除模型',
	'add_myself_model' => '添加自己的模型',
	'when_create_model' => '当模型建立完成时，模型在',
	'when_create_model_1' => '中是不开启的，您必须<u>启用频道</u>后该频道才会显示在站点菜单上面.您可以通过',
	'when_create_model_2' => '"基本设置->频道操作->功能频道设置"</a>来设置',
	'when_create_model_3' => '所有模型文件存放在 model 文件夹下面，系统母板存放在 mthemes 目录中，建立好的模型存放在 model/data 目录中.您可以根据需要进行修改.',
	'model_info' => '模型信息',
	'is_use_model' => '是否启用',
	'select_changle_model' => '重新选择模板<p>此操作会将系统母板重新载入替换现有模板，现有模型模板中的数据将被清除.</p>',
	'table_initialization_error' => '数据表初始化失败，请确认下列这些表不在数据库中存在.<br />',
	'model_settings' => '模型设置',
	'model_name_about' => '模型标识 *<p>模型建立后,标识将不能修改. 标识只可以输入字母、数字，长度2-20个字符.</p>',
	'model_other_name_about' => '模型名称 *<p>将以模块名形式出现在前台.名称只可以输入中文、字母、数字、下划线，长度2-60个字符.</p>',
	'model_for_example' => '例如：商品模型',
	'allow_guest_about' => '允许游客投稿<p>此选项打开后游客可以投稿.</p>',
	'allow_post_about' => '允许投稿<p>此选项打开后在模型前台页面出现投稿链接，允许用户投稿.</p>',
	'allow_post_about_1' => '允许投稿 <p>选中此项时，模型配置同时开启允许投稿选项时，将会在在线投稿页面中出现.</p>',
	'allow_post' => '允许投稿',
	'allow_guest' => '允许游客投稿',
	'model_allowgrade_about' => '投稿需要审核<p>此选项打开后用户投搞文章需要管理员审核通过后，才在前台显示，允许投稿开启时才起作用.</p>',
	'model_allowgrade' => '投稿需要审核',
	'model_allowcomment_about' => '允许评论<p>打开后内容页将出现评论区.</p>',
	'model_allowcomment' => '允许评论',
	'model_allowrate_about' => '允许评分<p>打开后列表、内容页将"顶"字样图片，用户每顶一次加1分，此选项可用于排序.</p>',
	'model_allowrate' => '允许评分',
	'model_allowguestsearch_about' => '允许游客搜索<p>游客无需登录即可搜索.</p>',
	'model_allowguestsearch' => '允许游客搜索',
	'model_searchinterval_about' => '搜索间隔时间(秒)<p>0表示不限制</p>',
	'seconds' => '秒',
	'model_allowguestdownload_about' => '允许游客下载<p>游客无需登录即可下载.</p>',
	'model_allowguestdownload' => '允许游客下载',
	'model_downloadinterval_about' => '下载间隔时间(秒)<p>0表示不限制</p>',
	'model_allowfilter_about' => '允许词语过滤<p>按照站长在后台设置的词语过滤规则，对提交来的数据进行过滤.</p>',
	'model_allowfeed_about' => '允许加入事件',
	'model_allowfeed_item' => '信息',
	'model_allowfeed_re' => '回复',
	'model_allowfilter' => '允许词语过滤',
	'model_listperpage' => '列表页面显示条目数<p>0表示系统默认值，系统默认20条.</p>',
	'model_subject_pic' => '标题图片缩略图规格<p>默认规格400x300，信息查看页会有显示.</p>',
	'model_fielddefault' => '系统字段默认名称<p>这里可以修改系统字段的默认名称.系统默认值为<br />subject = 标题<br />subjectimage = 标题图片<br />catid = 系统分类<br />message = 内容</p>',
	'model_seokeywords' => '模型关键词<p>此选项为搜索优化(SEO)选项，将出现在meta name="keywords"中.</p>',
	'model_seodescription' => '模型描述<p>此选项为搜索优化(SEO)选项，将出现在meta name="description"中.</p>',
	'model_select_template' => '选择模板',
	'model_select_header_view' => '模板预览 （当鼠标移动到模板名称时显示）',
	'model_systemtpl_1' => '是否与系统模板同步<p>勾选后,模型模板会随系统模板(系统模板目录: mthemes/)而更改.如果您需要自定义或者有修改模型模板(模型模板目录: model/data/模型标识/)需求时,请不要勾选此选项.</p>',
	'model_select_tpl' => '模型模板',
	'model_systemtpl_2' => '与系统模板同步',
	'model_system_template' => '<li>系统内置了常见字段母板，而且我们仍在继续完善字段母板库.您可以通过"快速建立">>"<a href="javascript:;" onclick="fieldnav(this, \'simplefield\');">展开</a>"来将系统内置的母板字段复制到您的模型中，并加以改造为您所用.</li>',
	'add_myself_field' => '添加自己的字段.',
	'field_note' => '字段说明',
	'length' => '长度',
	'initialization_value' => '初始化值',
	'table_field_type' => '表单字段类型',
	'table_shows' => '列表显示',
	'contribution' => '投稿',
	'fixed_length' => '定长',
	'start' => '展开',
	'fast_create' => '快速建立',
	'user_defined_fields' => '用户自定义字段',
	'away' => '收起',
	'add_new_field' => '增加新字段',
	'field_name_about' => '字段名 *<p>字段名为建立数据表时而用，字段名称以字母开头，后面可以跟字母数字和下划线，长度2-30个字符，并且字段名不可为系统字段.系统字段请参照，浏览字段->系统字段->展开.</p>',
	'field_note_about' => '字段说明 *<p>用户前台看到的名称，例如：作者、价格.字段说明长度2-60个字符.</p>',
	'for_example_author' => '例如：作者',
	'table_field_about' => '表单字段类型 *<p>前台用户投稿和后台信息提交表单中输入时的样式.不同的字段类型决定着下面选项的不同.</p>',
	'view_backup' => '浏览备份',
	'model_compression_package' => '模型压缩包',
	'model_list' => '模型备份列表',
	'model_backup_manager' => '模型备份管理',
	'list_table_not_exists' => '以下数据表不存在<br />',
	'list_file_not_exists' => '以下文件不存在<br />',
	'model_dir_1' => '模型目录(',
	'model_dir_2' => ')下没有模型文件，请确认后重试.',
	'del_field' => '删除字段',
	'field_del_confirm' => '字段删除二次确认',
	'field_del_confirm_about' => '字段删除后将无法恢复，请您在删除前及时备份，以免造成不必要的损失.',
	'model_del_confirm' => '模型删除二次确认',
	'model_del_confirm_about' => '系统将删除与之相关的所有数据，并且不能恢复.包括数据表、模版文件，请您在删除前及时备份，以免造成不必要的损失.',
	'will_del' => '将删除',
	'information_index_table' => '信息索引表',
	'information_table' => '信息表',
	'comments_table' => '评论表',
	'score_table' => '评分表',
	'classification' => '分类表',
	'folder_table' => '文件夹表',
	'model_dir_file' => '模型目录及目录中的文件.',
	'varchar_name' => '变长字符型(VARCHAR)',
	'char_name' => '定长字符型(CHAR)',
	'text_name' => '小型字符型(TEXT)',
	'mediumtext_name' => '中型字符型(MEDIUMTEXT)',
	'longtext_name' => '大型字符型(LONGTEXT)',
	'tinyint_name' => '微小数值型(TINYINT)',
	'smallint_name' => '小数值型(SMALLINT)',
	'mediumint_name' => '中数值型(MEDIUMINT)',
	'int_name' => '大数值型(INT)',
	'bigint_name' => '超大数值型(BIGINT)',
	'float_name' => '单精密浮点数值型(FLOAT)',
	'double_name' => '双精密浮点数值型(DOUBLE)',
	'ishtml_about' => '是否以html显示 <p>允许字段保存html代码.</p>',
	'isfixed' => '是否存入定长表<p>为了加速列表浏览速度,可以将定长且需要在列表显示字段加入定长表.</p>',
	'ishtml' => '支持html代码',
	'allow' => '允许',
	'isrequired' => '是否必填 <p>字段在提交时必须填写.选中此项时，必须选中允许投稿.当允许投稿选中时，可以不选择此项，即允许投稿但非必填.</p>',
	'allowsearch_about' => '允许搜索 <p>选中此项时，前台列表、搜索页将允许用户对本字段进行搜索.</p>',
	'allowshow_about' => '允许显示 <p>选中此项时，本字段将在前台页面显示。当字段不允许显示时，可以通过后台查看。管理员可以通过权限管理给指定用户开通后台浏览权限，来实现诸如人才库等模型。</p>',
	'allowlist_about' => '允许列表显示 <p>选中此项时，本字段将在前台列表、搜索页同标题一起显示.当本选项选中时，必须选择选中允许显示.</p>',
	'field_default_value' => '初始化值<p>字段建立后的默认值，当提交表单未填写时起作用.</p>',
	'field_length' => '字段长度',
	'field_types_of_data_tables' => '数据表字段类型',
	'field_linkage' => '联动字段<p>请选择上一级字段,例如:本字段为"市",这里选择"省"字段. 为空时表示顶层字段,例如:本字段为"省",这里可以不选.</p>',
	'isbbcode' => '是否支持BBCODE代码<p>支持的代码:[b] [i] [u] [color] [size] [font] [align] [url] [email] [img]</p>',
	'block_isbbcode' => '支持BBCODE代码',
	'fielddata' => '表单显示元素 *<p>多个元素用"回车"格开,对select,linkage,radio,checkbox表单字段类型有效，每个元素将成为select,linkage,radio,checkbox类型的一个选项.</p>',
	'flash' => 'FLASH文件(flash)',
	'one_way_text_box' => '单行文本框(text)',
	'the_drop_down_box' => '下拉框(select)',
	'the_linkage_drop_down_box' => '联动下拉框(linkage)',
	'field_timestamp' => '时间戳(timestamp)',
	'single_radio' => '单选框(radio)',
	'checkbox' => '复选框(checkbox)',
	'textarea' => '多行文本框(textarea)',
	'y' => '<img src="'.S_URL.'/admin/images/ico_true.gif">',

	//admin/admin_modelfolders.php
	'folder_management' => '文件夹管理',
	'days' => '日期',
	'reduction' => '还原',
	'through_audit' => '审核通过',
	'moved_to_waste_bins' => '移至废件箱',

	//admin/admin_modelmanages.php
	'subject_pic' => '标题图片',
	
	'continue_to_release_new_information' => '继续发布新信息',
	'edit_this_page' => '编辑当前页',
	'list_info' => '信息列表',
	'select_info_date' => '信息发布日期<p>您可以自己指定当前资讯的发布日期。注意，不能是当前时间以后的日期。</p>',
	'select_info_date_title' => '信息发布日期',
	'content_title' => '内容',
	'download_title' => '下载',
	'fieldcomment_help' => '本字段支持HTML代码，换行请用&lt;br /&gt;.',
	'fieldcomment_discuz_code' => '支持BBCODE代码<p>支持的代码:[b] [i] [u] [color] [size] [font] [align] [url] [email] [img]</p>',
	'field_only_int' => '字段只支持数值型.',
	'field_only_float' => '字段只支持浮点型.',
	'field_length_1' => '长度在',
	'field_length_2' => '个字符之内.',
	'upload_fileext' => '只能上传图片类型文件(.jpg .jpeg .gif .png).',

	//admin/admin_modelperm.php
	'browser_model' => '浏览模型',
	'model_name' => '模型标识',

	//admin/include/admin_blocks_announcement.inc.php,
	'space_showmultipage_0' => '显示指定数目的信息',
	'space_showmultipage_1' => '读取所有满足条件的信息，并分页显示',
	'block_announcement_title_settid' => '指定公告id(s)',
	'block_thread_settid_0' => '不指定',
	'block_thread_settid_1' => '指定',
	'block_announcement_title_tid' => '输入公告id(s)<p>多个用半角逗号,隔开</p>',
	'block_announcement_title_author' => '公告发布用户名(s)',
	'block_thread_title_order' => '列表排序',
	'block_announcement_order_displayorder' => '显示顺序',
	'block_announcement_order_starttime' => '开始时间',
	'block_announcement_order_endtime' => '结束时间',
	'block_thread_title_showmultipage' => '数据显示数目设置',
	'block_thread_title_start' => '起始数据行数',
	'block_thread_title_limit' => '显示数据条数',
	'block_thread_title_multipageexplain' => '分页调用说明',
	'block_thread_multipageexplain' => '启用数据分页显示后，在下面的"显示风格"配置环节，您必须指定"变量名"，并且模块风格文件只能选择"只获取数据"，此外，缓存更新时间设置将无效，数据不会被缓存。<br>列表信息将储存到 <b><i>$_SBLOCK[变量名]</i></b> 变量中<br>分页信息将储存到 <b><i>$_SBLOCK[变量名_multipage]</i></b> 变量中<br>您只需要在模板中对列表变量、分页变量加以灵活利用就可以了',
	'block_thread_title_perpage' => '每页显示数目<p>默认为20</p>',
	'block_thread_title_subjectlen' => '标题长度',
	'block_thread_title_subjectdot' => '标题截取省略号',
	'block_dot_0' => '无省略号',
	'block_dot_1' => '有省略号',
	'block_title_showdetail' => '读取详细内容信息<p>读取详细内容信息，这将增加服务器负担。如果您只想获取标题列表，请不要选择该项。</p>',
	'block_showdetail_0' => '不读取',
	'block_showdetail_1' => '读取',
	'block_title_showdetail_image' => '读取封面图片和详细信息',
	'block_thread_title_messagelen' => '内容长度',
	'block_thread_title_messagedot' => '内容截取省略号',

	//admin/include/admin_blocks_bbsattachment.inc.php,
	'block_attachment_filetype_image' => '图片',
	'block_attachment_filetype_file' => '文件',
	'block_thread_digest_1' => '精华I',
	'block_thread_digest_2' => '精华II',
	'block_thread_digest_3' => '精华III',
	'block_attachment_title_setaid' => '指定论坛附件aid(s)',
	'block_attachment_title_aid' => '输入论坛附件aid(s)',
	'block_attachment_title_filetype' => '论坛附件类型',
	'block_attachment_title_dateline' => '论坛附件上传时间范围',
	'block_attachment_title_readperm' => '论坛附件权限积分范围',
	'block_attachment_title_downloads' => '论坛附件下载次数范围',
	'block_thread_title_fid' => '版块fid(s)',
	'block_thread_title_typeid' => '类别typeid(s)',
	'block_thread_title_dateline' => '发布时间范围',
	'block_thread_title_lastpost' => '回复时间范围',
	'block_thread_title_authorid' => '作者uid(s)',
	'block_thread_title_readperm' => '阅读权限范围<p>为空为不限制</p>',
	'block_thread_title_price' => '出售价格范围',
	'block_thread_title_views' => '查看数范围',
	'block_thread_title_replies' => '回复数范围',
	'block_thread_title_rate' => '主题评分范围',
	'block_thread_title_digest' => '精华级别',
	'block_thread_title_blog' => '加入论坛文集',
	'block_thread_blog_0' => '不限制',
	'block_thread_blog_1' => '加入到论坛文集',
	'block_thread_title_closed' => '关闭主题',
	'block_thread_closed_0' => '不限制',
	'block_thread_closed_1' => '主题关闭',
	'block_attachment_order_downloads' => '下载次数',
	'block_attachment_order_filesize' => '文件大小',
	'block_attachment_order_dateline' => '上传时间',
	'block_attachment_thread_order_displayorder' => '主题显示顺序',
	'block_attachment_thread_order_dateline' => '主题发布时间',
	'block_attachment_thread_order_lastpost' => '主题最后回复',
	'block_attachment_thread_order_views' => '主题查看数',
	'block_attachment_thread_order_replies' => '主题回复数',
	'block_attachment_thread_order_digest' => '主题精华级别',
	'block_attachment_thread_order_rate' => '主题评分分数',
	'block_attachment_thread_order_readperm' => '主题阅读积分',
	'block_attachment_thread_order_price' => '主题购买积分',
	'block_attachment_title_descriptionlen' => '附件介绍长度',
	'block_attachment_title_descriptiondot' => '附件介绍截取省略号',

	//admin/include/admin_blocks_bbsforum.inc.php,
	'block_forum_type_group' => '大分类',
	'block_forum_type_forum' => '版块',
	'block_forum_type_sub' => '子版块',
	'block_forum_allow_0' => '不限制',
	'block_forum_allow_1' => '开启',
	'block_thread_bbsurltype_site' => '文章系统模式查看',
	'block_thread_bbsurltype_bbs' => '直接进入论坛查看',
	'block_forum_title_setfid' => '指定版块fid(s)',
	'block_forum_title_fid' => '输入版块fid(s)<p>多个用半角逗号,隔开</p>',
	'block_forum_title_fup' => '上级论坛fid(s)',
	'block_forum_title_type' => '论坛类型',
	'block_forum_title_threads' => '论坛主题数范围',
	'block_forum_title_posts' => '论坛帖子数范围',
	'block_forum_title_todayposts' => '论坛今日发贴数范围',
	'block_forum_title_allowblog' => '板块允许其他模块共享',
	'block_forum_order_displayorder' => '显示顺序',
	'block_forum_order_threads' => '总主题数',
	'block_forum_order_posts' => '总帖子数',
	'block_forum_order_todayposts' => '今日发贴数',
	'block_thread_title_bbsurltype' => '帖子链接模式',
	'block_forum_title_descriptionlen' => '版块介绍长度',
	'block_forum_title_descriptiondot' => '版块介绍截取省略号',

	//admin/include/admin_blocks_bbslink.inc.php,
	'block_link_title_setid' => '指定论坛友情链接id(s)',
	'block_link_title_id' => '输入论坛友情链接id(s)<p>多个用半角逗号,隔开</p>',
	'block_link_title_note' => '友情链接介绍',
	'block_link_note_0' => '不限制',
	'block_link_note_1' => '有介绍',
	'block_link_title_logo' => '友情链接图标',
	'block_link_logo_0' => '不限制',
	'block_link_logo_1' => '有图标',
	'block_link_order_id' => '添加顺序',
	'block_link_title_namelen' => '链接名长度',
	'block_link_title_namedot' => '链接名截取省略号',
	'block_link_title_notelen' => '链接介绍长度',
	'block_link_title_notedot' => '链接介绍截取省略号',

	//admin/include/admin_blocks_bbsmember.inc.php,
	'block_member_title_setuid' => '指定用户uid(s)',
	'block_member_title_uid' => '输入用户uid(s)',
	'block_member_title_groupid' => '用户组id(s)',
	'block_member_title_regdate' => '注册时间范围',
	'block_member_title_lastvisit' => '上次访问时间范围',
	'block_member_title_lastpost' => '上次发贴时间范围',
	'block_member_title_posts' => '用户发贴数范围',
	'block_member_title_digestposts' => '用户精华贴数范围',
	'block_member_title_oltime' => '用户在线时间范围<p>单位为秒</p>',
	'block_member_title_pageviews' => '用户页面浏览数范围',
	'block_member_title_credits' => '用户积分数范围',
	'block_member_title_credits1' => '用户扩展积分1数范围',
	'block_member_title_credits2' => '用户扩展积分2数范围',
	'block_member_title_credits3' => '用户扩展积分3数范围',
	'block_member_title_credits4' => '用户扩展积分4数范围',
	'block_member_title_credits5' => '用户扩展积分5数范围',
	'block_member_title_credits6' => '用户扩展积分6数范围',
	'block_member_title_credits7' => '用户扩展积分7数范围',
	'block_member_title_credits8' => '用户扩展积分8数范围',
	'block_member_order_posts' => '发贴数',
	'block_member_order_digestposts' => '精华贴数',
	'block_member_order_oltime' => '在线时间',
	'block_member_order_pageviews' => '页面浏览数',
	'block_member_order_credits' => '积分',
	'block_member_order_credits1' => '扩展积分1',
	'block_member_order_credits2' => '扩展积分2',
	'block_member_order_credits3' => '扩展积分3',
	'block_member_order_credits4' => '扩展积分4',
	'block_member_order_credits5' => '扩展积分5',
	'block_member_order_credits6' => '扩展积分6',
	'block_member_order_credits7' => '扩展积分7',
	'block_member_order_credits8' => '扩展积分8',
	'block_member_order_regdate' => '注册时间',
	'block_member_order_lastvisit' => '上次访问时间',
	'block_member_order_lastpost' => '上次发贴时间',
	'block_member_order_lastactivity' => '上次活动时间',
	'block_member_title_signaturelen' => '用户签名长度',
	'block_member_title_signaturedot' => '签名截取省略号',

	//admin/include/admin_blocks_bbspost.inc.php,
	'block_post_title_setpid' => '指定帖子pid(s)',
	'block_post_title_pid' => '输入帖子pid(s)',
	'block_post_title_tid' => '帖子所在主题tid(s)',
	'block_post_title_first' => '第一个主题贴',
	'block_post_first_0' => '不限制',
	'block_post_first_1' => '是主题贴',
	'block_thread_title_attachment' => '包含附件',
	'block_thread_attachment_0' => '不限制',
	'block_thread_attachment_1' => '主题包含附件',
	'block_thread_attachment_4' => '主题包含图片',
	'block_thread_order_dateline' => '发布时间',

	//admin/include/admin_blocks_bbsthread.inc.php,
	'block_thread_title_settid' => '指定特定主题',
	'block_thread_title_tid' => '输入主题tid(s)<p>多个用半角逗号,隔开</p>',
	'block_thread_title_poll' => '投票主题',
	'block_thread_poll_0' => '不限制',
	'block_thread_poll_1' => '是投票主题',
	'block_thread_attachment_2' => '主题包含图片附件',
	'block_thread_attachment_3' => '主题包含文件附件',
	'block_thread_order_displayorder' => '置顶级别',
	'block_thread_order_lastpost' => '回复时间',
	'block_thread_order_views' => '查看数',
	'block_thread_order_replies' => '回复数',
	'block_thread_order_digest' => '精华级别',
	'block_thread_order_rate' => '评分值',
	'block_thread_order_readperm' => '查看权限',
	'block_thread_order_price' => '购买积分',

	//admin/include/admin_blocks_category.inc.php,
	'block_cat_isroot_0' => '不限制',
	'block_cat_isroot_1' => '是',
	'block_cat_isroot_2' => '否',
	'block_cat_title_setcatid' => '指定分类ID',
	'block_cat_title_catid' => '输入分类ID',
	'block_cat_title_type' => '分类归属系统',
	'block_cat_title_upid' => '上级分类ID',
	'block_cat_title_isroot' => '是否根分类',
	'block_cat_order_displayorder' => '显示顺序',

	//admin/include/admin_blocks_poll.inc.php,
	'block_poll_title_setpollid' => '指定投票的id(s)',
	'block_poll_title_pollid' => '输入投票的id(s)',
	'block_poll_title_dateline' => '发起日期范围',
	'block_poll_order_dateline' => '发起日期',
	'block_poll_order_pollnum' => '参与人数',

	//admin/include/admin_blocks_spacecomment.inc.php,
	'block_spacecomment_title_setcid' => '指定评论的CID',
	'block_spacecomment_title_cid' => '输入评论的CID(S)',
	'block_spacecomment_title_type' => '系统类型',
	'block_spacecomment_title_itemid' => '被评论的主题的ID(S)',
	'block_spacecomment_title_uid' => '被评论的主题的作者ID(S)',
	'block_spacecomment_title_authorid' => '评论作者ID(S)',
	'block_spacecomment_order_dateline' => '评论时间',
	'block_spacecomment_order_rates' => '评论分数',

	//admin/include/admin_blocks_spaceitem.inc.php,
	'block_spaceitem_title_grade' => '审核等级',
	'block_spaceitem_title_catid' => '站点分类',
	'block_spaceitem_title_haveattach' => '包含附件',
	'block_spaceitem_title_digest' => '精华级别',
	'block_spaceitem_title_top' => '置顶级别',
	'block_spaceitem_title_dateline' => '发布时间范围',
	'block_spaceitem_title_lastpost' => '最后回复范围',
	'block_spaceitem_title_uid' => '指定作者uid',
	'block_spaceitem_title_viewnum' => '查看数范围',
	'block_spaceitem_title_replynum' => '回复数范围',
	'block_showattach_0' => '不读取',
	'block_showattach_1' => '读取',
	'block_thread_title_showcategory' => '读取所在分类栏目名',
	'block_spaceitem_title_click35' => '支持数',
	'block_spaceitem_title_click36' => '反对数',
	'block_spaceitem_title_click' => '热度',

	//admin/include/admin_blocks_spacetag.inc.php,
	'block_spacetag_title_tagid' => '输入TAG id(s)',
	'block_spacetag_title_type' => '系统类型',
	'block_spacetag_title_dateline' => '信息发布时间',
	'block_spacetag_order_dateline' => '发布时间',

	//admin/include/admin_blocks_tag.inc.php,
	'block_tag_title_settagid' => '指定TAG id(s)',
	'block_tag_title_tagid' => 'TAG id(s)',
	'block_tag_title_dateline' => '创建时间',
	'block_tag_title_uid' => '创建者UID',
	'block_tag_order_spacenewsnum' => '资讯数',

	//admin/include/admin_blocks_uchblog.inc.php,
	'block_uchblog_title_setblogid' => '指定UCH日志 id(s)',
	'block_uchblog_title_blogid' => '输入UCH日志 id(s)',
	'block_uchblog_title_pic' => '是否含有图片',
	'block_uchblog_title_dateline' => '日志发布时间',
	'block_uchblog_title_uid' => '作者uid(s)',
	'block_uchblog_title_views' => '查看数范围',
	'block_uchblog_title_replies' => '回复数范围',
	'block_uchblog_order_dateline' => '日志发布时间',
	'block_uchblog_order_views' => '日志查看数',
	'block_uchblog_order_replies' => '日志回复数',
	'noyes' => '忽略',

	//admin/include/admin_blocks_uchspace.inc.php,
	'block_uchspace_title_setuid' => '指定UCH个人空间uid(s)',
	'block_uchspace_title_uid' => '输入UCH个人空间uid(s)',
	'block_uchspace_title_dateline' => '空间建立时间',
	'block_uchspace_title_updatetime' => '最后更新时间',
	'block_uchspace_title_views' => '空间查看数',
	'block_uchspace_title_friendnum' => '好友数量',
	'block_uchspace_title_avatar' => '是否含有头像',

	//admin/include/admin_blocks_uchphoto.inc.php,
	'block_uchphoto_title_setalbumid' => '指定UCH相册 id(s)',
	'block_uchphoto_title_albumid' => '输入UCH相册 id(s)',
	'block_uchphoto_title_dateline' => '相册建立时间',
	'block_uchphoto_title_updatetime' => '相册最后更新时间',
	'block_uchphoto_title_picnum' => '相册照片数',

	//other,
	'common_note' => '提示说明',
	'button_ok' => '确定',
	'category_title_upid' => '上级分类',
	'category_title_tpl' => '分类页面模板文件<p>您可以为该分类指定一个模板文件。模板文件必须放置在指定的目录下面，且后缀为 .html.php 。当指定的模板文件不存在的时候，则使用默认模板。</p>',
	'category_copy_tpl' => '分类页面模板文件</p>',
	'category_title_view_tpl' => '查看当前分类文章页面模板<p>您可以为该分类文章指定一个模板文件。模板文件必须放置在指定的目录下面，且后缀为 .html.php 。当指定的模板文件不存在的时候，则使用默认模板。</p>',
	'category_copy_view_tpl' => '查看当前分类文章页面模板</p>',
	'category_title_icon' => '封面图片<p>您可以为分类设置一个介绍性的封面图片</p>',
	'category_title_icon_delete' => '删除封面图片',
	'category_title_displayorder_title' => '显示顺序',
	'category_title_url' => '跳转链接<p>输入一个URL地址，则浏览该分类时，页面自动跳转到指定的链接地址。</p>',
	'category_copy_url' => '跳转链接',
	'category_title_note' => '说明介绍',
	'category_title_bbsmodel' => '读取论坛资源',
	'category_title_subcatid' => '扩展读取分类设置<p>通过该设置，您可以设置当前分类下面同时也读取其他分类的信息资源。默认只读取当前分类信息资源。</p>',
	'category_copy_subcatid' => '扩展读取分类设置',
	'category_title_newcatid' => '请选择您的动作<p>合并将删除原有的分类</p>',
	'spacenews_title_newsauthor' => '原创作者',
	'spacenews_title_newsfrom' => '信息来源',
	'spacenews_title_newsfromurl' => '信息来源URL',
	'spacenews_title_message_page' => '资讯分页信息',
	'spacenews_title_message_send' => '资讯分页定位',
	'spacenews_title_message_send' => '资讯分页定位',
	'spacenews_title_message_start' => '第一页',
	'spacenews_title_message_end' => '尾页',
	'spacenews_title_message_no1' => '设为第',
	'spacenews_title_message_no2' => '页',
	'spacenews_title_message_op' => '资讯分页<p>您可以为该信息进行分页</p>',
	'spacenews_title_message' => '资讯内容',
	'spacenews_title_upload' => '内容附件<p>您可以上传多个附件，其中，列表中的选中图片附件将作为该资讯的封面图片。<font color=red>注意，上传的附件必须要插入到内容中才能正常显示。</font></p>',
	'spacenews_title_newsurl' => '外部链接URL<p>如果填入外部链接，查看该资讯时，将自动跳转到该链接。</p>',
	'customfield_title_customfield' => '自定义字段<p>字段类型为列表框、复选框时，您需要指定列表选项。列表选项中每一行文字代表一个选项</p>',
	'style_tpltype' => '模块<p>请为该风格指定一个模块。只有指定的模块，才可以使用本风格</p>',
	'style_tplname' => '风格方案名',
	'style_tplfilepath' => '风格模板文件地址<p>请选择现有的模块风格文件。也可以新建一个模块风格文件，文件后缀名必须为 .html.php ，并且上传到 styles 目录下面</p>',
	'style_tplnote' => '详细说明<p>对本风格具体的显示样式作详细介绍说明</p>',
	'style_default_tplname' => '只获取数据',
	'style_default_tplnote' => '风格作用:获取数据集合到用户指定的模块变量中<br>展示方式:无<br>使用说明:用户可以在模板页面中利用获取到的<br>模块变量 $_SBLOCK[变量名] 自由设置展示方式',
	'robot_name' => '机器人名',
	'robot_listurltype' => '索引页面URL地址方式',
	'robot_allnum' => '采集总个数',
	'robot_pernum' => '单次采集个数<p>视网速而定，建议设置小一些，以免超时</p>',
	'robot_encode' => '采集页面编码<p>请输入要采集页面的编码。比如：gbk、utf-8、big5。为空则不进行编码转换</p>',
	'robot_savepic' => '保存内容中的图片到本地',
	'robot_saveflash' => '保存内容中的FLASH到本地',
	'robot_list' => '列表页面采集设置',
	'robot_subjecturlrule' => '列表区域识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[list]" disabled="disabled" /></p><p>如&lt;td&gt;文章列表&lt;/td&gt;<p>规则就是&lt;td&gt;[list]&lt;/td&gt;</p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_subjecturllinkrule' => '文章链接URL识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[url]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_subjecturllinkpre' => '文章链接URL补充前缀',
	'robot_subjectrule' => '文章标题识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[subject]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_subjectfilter' => '文章标题过滤规则<p>用 * 来代替任意字符、换行、回车</p><p>多个规则之间用 | 隔开</p>',
	'robot_subjectreplace_title' => '文章标题文字替换',
	'robot_subjectkey' => '文章标题包含关键字<p>设置该选项后，则只采集标题包含关键字的文章</p><p>多个关键字之间用 | 隔开</p>',
	'robot_subjectkeycancel' => '文章标题关键字剔除过滤<p>设置该选项后，不会采集标题包含关键字的文章</p><p>多个关键字之间用 | 隔开</p>',
	'robot_messagekey' => '文章内容包含关键字<p>设置该选项后，则只采集文章内容包含关键字的文章</p><p>多个关键字之间用 | 隔开</p>',
	'robot_messagekeycancel' => '文章内容关键字剔除过滤<p>设置该选项后，不会采集文章内容包含关键字的文章</p><p>多个关键字之间用 | 隔开</p>',
	'robot_message' => '内容页面采集设置',
	'robot_fromrule' => '信息来源识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[from]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_authorrule' => '作者识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[author]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车. 也可以指定多个作者,采集结果在入库时随机抽取其中的一个.多个作者之间用 | 隔开,在指定多个作者时,不能出现标记符([author]).</p>',
	'robot_messagerule' => '文章内容识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[message]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_messagefilter' => '文章内容过滤规则<p>用 * 来代替任意字符、换行、回车</p><p>多个规则之间用 | 隔开</p>',
	'robot_messagepagetype' => '文章内容分页模式<p>当选择上下页导航时,"分页区域识别规则"请将下一页配置成识别区域.</p>',
	'robot_messagepagerule' => '文章内容分页区域识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[pagearea]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_messagepageurlrule' => '文章内容分页链接识别规则<p>截取的地方加上<input type="input" name="tmp[]" size="10" value="[page]" disabled="disabled" /></p><p>用 * 来代替任意字符、换行、回车</p>',
	'robot_messagereplace_title' => '文章内容文字替换',
	'robot_picurllinkpre' => '图片/FLASH链接的URL补充前缀',
	'robot_messagepageurllinkpre' => '文章内容分页链接URL补充前缀',
	'robot_subjectallowrepeat' => '允许文章标题重复<p>(<strong style="color:red">如果启用自动入库再启用此项文章标题不允许重复将加重数据库的负载</strong>)</p>',
	'robot_import_title' => '导入机器人',
	'robot_import_text' => '配置文件内容<p>请将导出的文件内容粘贴到文本框</p>',
	'robot_import_ignoreversion' => '允许导入不同版本<p>如果允许的话，易产生不兼容错误</p>',
	'robot_main' => '基本设置',
	'robot_importcatid' => '自动导入到<p>选择资讯分类，可以直接将采集的结果导入到资讯库中</p>',
	'robot_dateline' => '预定义发布时间<p>导入资讯分类以后，定义的发布时间</p>',
	'robotmessage_title_author' => '作者',
	'robotmessage_title_itemfrom' => '来源',
	'robotmessage_title_dateline' => '发布时间',
	'robotmessage_title_message' => '内容',
	'robotmessage_title_picurls' => '包含图片',
	'robotmessage_title_flashurls' => '包含FLASH',
	'robotmessage_title_isimport' => '是否采用',
	'robotmessage_import_category' => '选择分类',
	'robotmessage_import_delete' => '导入后删除',
	'space_title_catid' => '系统分类*<p>请为您的信息正确选择一个系统分类，便于信息被更多的人查看到</p>',
	'space_title_tagname' => 'TAG<p>TAG就是一篇信息的关键字，只能包含汉英数和下划线，长度不超过10个字符。多个TAG之间用半角空格隔开。</p>',
	'space_title_digest' => '精华级别',
	'space_title_top' => '置顶级别',
	'space_title_allowreply' => '允许评论',
	'space_op_category' => '选择分类',
	'space_op_folder' => '选择文件夹',
	'space_hot_tag' => '最热TAG',
	'space_last_tag' => '我的TAG',
	'space_add_tag' => '添加',
	'space_order_0' => '第一排序',
	'space_order_1' => '第二排序',
	'space_order_2' => '第三排序',
	'space_order_asc' => '递增',
	'space_order_desc' => '递减',
	'space_date_null' => '---不限制---',
	'space_date_day_1' => '一天以来',
	'space_date_day_2' => '两天以来',
	'space_date_week_1' => '一周以来',
	'space_date_week_2' => '两周以来',
	'space_date_month_1' => '一个月以来',
	'space_date_month_3' => '三个月以来',
	'space_date_month_6' => '六个月以来',
	'space_date_year_1' => '一年以来',
	'prefield_title_field' => '字段名',
	'prefield_title_value' => '可选值',
	'prefield_title_isdefault' => '默认选中',
	'prefield_option_mood' => '选择心情',
	'prefield_option_weather' => '选择天气',
	'prefield_option_newsauthor' => '选择作者',
	'prefield_option_newsfrom' => '选择来源',
	'prefield_option_filesizeunit' => '选择大小单位',
	'prefield_option_version' => '选择版本',
	'prefield_option_producer' => '选择开发商',
	'prefield_option_downfrom' => '选择来源',
	'prefield_option_language' => '选择语言',
	'prefield_option_permission' => '选择授权形式',
	'prefield_option_system' => '选择平台',
	'prefield_option_cachetime' => '选择时间',
	'prefield_title_isdefault' => '默认选中',
	'prefield_title_isdefault' => '默认选中',
	'poll_title_subject' => '投票主题',
	'poll_title_ismulti' => '投票类型',
	'poll_title_summary' => '投票介绍',
	'poll_title_options' => '投票选项',
	'block_filter' => '过滤设置',
	'block_order' => '排序设置',
	'block_limit' => '数据设置',
	'block_template' => '显示风格',
	'block_batch' => '显示处理',
	'block_cache' => '缓存设置',
	'block_type_category' => '系统分类',
	'block_type_bbsthread' => '论坛主题',
	'block_type_bbsannouncement' => '论坛公告',
	'block_type_bbsforum' => '论坛版块',
	'block_type_bbslink' => '论坛友情链接',
	'block_type_bbsmember' => '论坛会员',
	'block_type_bbspoll' => '论坛投票',
	'block_type_bbspost' => '论坛帖子',
	'block_type_bbsattachment' => '论坛附件',
	'block_type_friendlink' => '站点友情链接',
	'block_type_spacenews' => '资讯',
	'block_type_spaceimage' => '图片',
	'block_type_poll' => '投票',
	'block_type_tag' => 'TAG',
	'block_type_model' => '模型',
	'block_type_spacetag' => 'TAG文章信息',
	'block_type_spaceuserlink' => '用户友情链接',
	'block_type_spacecomment' => '用户回复',
	'block_type_spacefriend' => '我的好友',
	'block_type_archive' => '月份存档',
	'block_type_announcement' => '站点公告',
	'block_title_blockname' => '模块名',
	'block_title_blockname_model' => '模型名',
	'block_title_blockname_spacenews' => '频道名',
	'block_title_blockname_postitem' => '频道名',
	'block_type_uchblog' => 'UCH日志',
	'block_type_uchphoto' => 'UCH相册',
	'block_type_uchspace' => 'UCH个人空间',
	'block_type_postitem' => '文章投稿',
	'block_title_addblocktype' => '选择基本模块',
	'block_title_blockmodel' => '向导模式',
	'block_title_sql' => '输入查询SQL文<p>只支持SELECT开头的查询语句</p>',
	'block_spacenews_title_setitemid' => '指定资讯的itemid(s)',
	'block_spacenews_title_itemid' => '输入资讯的itemid(s)',
	'block_model_title_setitemid' => '指定模型内容的itemid(s)',
	'block_postitem_title_setitemid' => '指定投稿内容的itemid(s)',
	'block_model_title_itemid' => '输入模型内容的itemid(s)',
	'block_postitem_title_itemid' => '输入投稿内容的itemid(s)',
	'attachmenttype_title_fileext' => '文件后缀',
	'attachmenttype_title_maxsize' => '大小限制<p>单位为KB</p>',
	'tag_close_exlain' => '选择状态',
	'tag_target' => '目的TAG名',
	'tag_title_tagname' => 'TAG名',
	'tag_title_relativetags' => '关联TAG名',
	'spacecache_cachetype' => '选择模块类型<p>在同一个缓存表中，不同类型的模块有不同的缓存数据，请选择要更新的缓存模型(<strong style="color:red">全不选为全部更新</strong>)</p>',
	'spacecache_cachekind' => '选择模块缓存系统<p>缓存按照不同的系统存放于不同的缓存表中，请选择要更新的缓存系统(<strong style="color:red">全不选为全部更新</strong>)</p>',
	'spacecache_title_file' => '文件缓存',
	'spacecache_filekind' => '缓存文件类型<p>系统将部分数据以文件的方式进行高速缓存以提高运行速度。请选择要更新的缓存文件类型(<strong style="color:red">全不选为全部更新</strong>)</p>',
	'cron_type_system' => '系统',
	'cron_type_user' => '用户',
	'cron_title_name' => '任务名称',
	'cron_title_available' => '任务状态',
	'cron_title_weekday' => '星期<p>设置每星期几执行本任务，"*"为不限制，本设置会覆盖下面的"日"设定</p>',
	'cron_title_day' => '日<p>设置哪一日执行本任务',
	'cron_title_hour' => '小时<p>设置哪一小时执行本任务</p>',
	'cron_title_minute' => '分钟<p>设置哪些分钟执行本任务</p>',
	'cron_title_filename' => '任务脚本<p>设置本任务的执行程序文件名，请勿包含路径，程序脚本统一存放于 ./include/cron/ 目录中</p>',
	'setting_title_timeoffset' => '系统默认时区',
	'setting_title_template' => '站点风格目录',
	'setting_title_gzipcompress' => '页面GZIP压缩',
	'setting_title_urltype' => '站点链接URL方式<p>您可以根据自己的服务器情况选择合适的URL方式</p>',
	'setting_news_html' => '资讯静态化选择<br /><p>传统模式:动态生成，适合用户浏览<p><p>优化模式:全部静态生成，SEO效果好<p>',
	'nomarl_makehtml' => '传统静态模式',
	'all_makehtml' => '优化静态模式',
	'setting_title_sitename' => '站点名称',
	'setting_title_closesite' => '暂时关闭站点',
	'setting_closesite_0' => '站点开放',
	'setting_closesite_1' => '站点关闭',
	'setting_closemessage' => '关闭站点的原因',
	'setting_registerrule' => '注册服务条款<p>用户注册的时候会显示并需要接受的服务条款。（支持html语言，换行使用&lt;br&gt;）</p>',
	'setting_title_bbsurltype' => '论坛、uchome链接URL方式<p>设置当站点上面读取论坛版块列表,uchome日志，相册后，用户点击相关内容是直接进入相关应用查看，还是使用站点模式查看</p>',
	'setting_title_pagepostfix' => '站点链接URL后缀<p>仅在站点链接URL方式为简短模式下有效</p>',
	'setting_title_htmldir' => 'HTML存放目录<p>可以为服务器绝对目录或者以 ./ 开头的相对目录(末尾不要加 / )</p>',
	'setting_title_htmlurl' => 'HTML的URL地址<p>如果您的HTML存放目录为 ./ 开头的相对目录，该选项可以为空。否则，请填入以http://开头的URL地址(末尾不要加 / )</p>',
	'setting_title_attachmentdir' => '站点附件目录<p>可以为服务器绝对目录或者以 ./ 开头的相对目录(末尾不要加 / )</p>',
	'setting_title_attachmenturl' => '站点附件URL地址<p>如果您的站点附件目录为 ./ 开头的相对目录，该选项可以为空。否则，请填入以http://开头的URL地址(末尾不要加 / )</p>',
	'setting_title_attachmentdirtype' => '站点附件归类方式',
	'setting_title_register' => '站点是否开放注册',
	'setting_title_debug' => '显示程序运行信息',
	'setting_title_watermark' => '图片添加水印',
	'setting_title_watermarkfile' => '水印图片文件地址<p>支持GIF和PNG两种水印图片，且GD库必须支持GIF和PNG</p>',
	'setting_title_watermarkstatus' => '水印放置位置',
	'setting_title_watermarktrans' => '水印融合度<p>设置水印图片与原始图片的融合度，范围为 1~100 的整数，数值越大水印图片透明度越低</p>',
	'setting_title_watermarkjpgquality' => '图片生成质量<p>设置添加水印后的图片质量，范围为 1~100 的整数，数值越大质量越高，但是图片大小也越大</p>',
	'setting_title_thumbbgcolor' => '缩略图背景色',
	'setting_title_thumboption' => '缩略图缩放模式',
	'setting_title_thumbcutmode' => '缩略图剪贴模式',
	'setting_title_thumbcutstartx' => '剪切的起始横坐标<p>单位:像素(px)</p>',
	'setting_title_thumbcutstarty' => '剪切的起始纵坐标<p>单位:像素(px)</p>',
	'setting_title_swatermark' => '水印设置',
	'setting_title_thumb' => '缩略图设置',
	'setting_title_html' => 'HTML设置',
	'setting_title_dir' => '本地路径设置',
	'setting_title_bbs' => '论坛设置',
	'setting_title_allowguest' => '开放游客评论',
	'setting_title_allowguestsearch' => '开放游客搜索',
	'setting_title_allowguestdownload' => '开放游客下载附件',
	'setting_title_allowtagshow' => '启用TAG秀功能<p>开启本功能后，系统会自动选取热门tag，并在内容中自动加入tag链接<p>',
	'setting_title_cache' => '缓存设置',
	'setting_title_allowcache' => '启用缓存<p>强烈建议开启。不开启的话，将严重影响服务器负载</p>',
	'setting_title_cachemode' => '缓存存储方式',
	'setting_cachemode_database' => '存储到数据库',
	'setting_cachemode_file' => '存储到文本',
	'setting_title_rss' => 'RSS设置',
	'setting_title_rssnum' => '默认RSS记录数',
	'setting_title_rssupdatetime' => 'RSS缓存自动更新间隔',
	'setting_title_needcheck' => '信息需要等级审核后才显示<p>选择该项后，用户发布的信息必须经过等级审核后才会在站点的聚合页面上显示</p>',
	'setting_title_checkgrade' => '自定义审核等级别名<p>系统提供五个等级的信息审核级别，您可以为这五个审核等级指定别名</p>',
	'setting_title_miibeian' => '网站备案信息<p>请输入您的网站在信息产业部的备案信息，例如:京ICP备04000001号</p>',
	'setting_title_search_wait' => '搜索间隔时间(秒)<p>0表示不限制</p>',
	'html_title_update' => 'HTML更新',
	'admin_func_digest' => '精华',
	'admin_func_top' => '置顶',
	'admin_func_noreply' => '不允许评论',
	'admin_func_attachment' => '包含附件',
	'admin_func_pic' => '包含图片',
	'userhtml_op_delete' => 'HTML删除',	
	'check_explain_title' => '提示说明',
	'bbsimport_no_exist' => '您指定的论坛主题内容不存在，请检查您的推送操作',
	'tpl_title_filename' => '文件名<p>要添加的文件名</p><p>请不要输入文件名后缀部分</p>',
	'tpl_delete_confirm' => '您确定要删除该文件？',
	'channel_action' => '英文ID<p>为频道指定一个唯一的英文ID，指定后不可以修改</p>',
	'channel_usesample' => '生成基本运行文件<p>选择该项，则系统会为该频道生成基本的PHP程序文件和模板文件</p>',
	'html_func_thumb_local' => '本地上传',
	'html_func_thumb_remote' => '远程上传',
	'html_func_thumb_batch' => '批量上传',
	'html_func_thumb_select_file' => '选择文件',
	'html_func_thumb_upload' => '上传',
	'html_func_thumb_explain' => '上传说明',
	'html_func_thumb_url' => '输入网址',
	'spaceimage_delete_images' => '全部清空',
	'examination_grades' => '审核等级',
	'batch_management_annex' => '批量附件管理',
	'no_use_of_annex' => '未使用附件',
	'notes_unused_annex' => '<p>上传后并没有使用的附件</p>',
	'photo_annex' => '图片附件',
	'annex_photo' => '附件为图片',
	'upload_who_channels' => '上传者UID<p>多用户UID中间请用半角逗号 "," 分割</p>',
	'upload_time_frame' => '上传时间范围<p>格式 yyyy-mm-dd，不限制请保留为空</p>',
	'keyword_document' => '文件名关键字<p>多关键字中间请用半角逗号 "," 分割</p>',
	'annex_on_keywords' => '附件介绍关键字<p>多关键字中间请用半角逗号 "," 分割</p>',
	'detailed_listings_show' => '显示详细列表',
	'annex_table_shows_details' => '显示详细附件列表',
	'annex_search' => '查找附件',
	'annex_to_meet_several_conditions' => '符合条件的附件数',
	'batch_deletion' => '批量删除附件',
	'batch_management_commentary' => '批量评论管理',
	'author_uid' => '作者UID<p>多用户UID中间请用半角逗号 "," 分割</p>',
	'author_info' => '作者名<p>多用户名中间请用半角逗号 "," 分割</p>',
	'keyword_content' => '内容关键字<p>多关键字中间请用半角逗号 "," 分割</p>',
	'made_time_frame' => '发表时间范围<p>格式 yyyy-mm-dd，不限制请保留为空</p>',
	'information_types' => '信息类型',
	'author_ip_info' => '作者IP<p>用*代表0~255之间的任意数字，例如10.0.*.1，则搜索发帖IP为10.0.0.1~10.0.255.1之间的内容</p>',
	'shows_a_detailed_list_of_comments' => '显示详细评论列表',
	'find_comments' => '查找评论',
	'batch_delete_comments' => '批量删除评论',
	'commenting_on_the_number_of_eligible' => '符合条件的评论数',
	'heading_keyword' => '标题关键字<p>多关键字中间请用半角逗号 "," 分割</p>',
	'information_state' => '信息状态',
	'normal_release' => '正常发布',
	'private_draft' => '私人草稿',
	'delete_recovery' => '删除回收',
	'shows_a_detailed_list_of_themes' => '显示详细主题列表',
	'find_theme' => '查找主题',
	'information_types_notes' => '<p>必须指定信息类型</p>',
	'table_shows_details' => '显示详细内容列表',
	'find_content' => '查找内容',
	'information_with_a_few_conditions' => '符合条件的信息数',
	'batch_delete_all_information' => '批量删除全部信息',
	'deleted_to_the_collection_points' => '删除到回收站',
	'delete_the_information_contained_in_annex' => '删除信息中的附件',
	'delete_specified_in_the_annex' => '删除指定信息中上传的附件',
	'information_deleted_comments' => '删除信息中的评论',
	'information_delete_all_the_comments' => '删除指定信息下的所有评论',
	'changing_the_state' => '改变信息状态',
	'batch_audited_information' => '批量审核信息等级',
	'submitted_operation' => '提交操作',
	'search_engine_optimization' => '搜索引擎优化',
	'additional_title_character' => '标题附加字',
	'other_information_head' => '其他头部信息',
	'sitemap_paper_maps' => 'sitemap地图文件',

	//admin/admincp_robots.php
	'add_a_new_link' => '增加新的列表页面链接',
	'for_example' => '例如',
	'robot_from' => '从',
	'robot_to' => '到',
	'wildcard_length' => '通配符长度',
	'wildcard_length_note' => '说明: 长度不足时，前面补0',

	//admin/admincp_reports.php	
	'report_title' => '举报信息',
	'not_translated_report' => '未处理的举报',
	'translated_report' => '已处理的举报',
	'cancel_report' => '忽略',
	'reporter' => '举报者',
	'translated_status' => '状态',
	'not_translated' => '未处理',
	'translated' => '已处理',
	'help_report' => '<ul><li>通过举报信息操作，管理人员可以对站内举报的信息进行忽略处理、删除处理，从而可以有效的控制站点页面上信息的内容显示。</li></ul>',

	//include/model_field.inc.php
	'information_id' => '信息id',
	'since_the_increase' => '自增',
	'information_type_id' => '信息分类id',
	'users_uid' => '用户uid',
	'introduction_forum_message_id' => '导入论坛帖子id',
	'information_title' => '信息标题',
	'score' => '评分',
	'add_time' => '添加时间',
	'last_reply_time' => '最后回复时间',
	'whether_to_allow_return' => '是否允许回复',
	'news_id' => '资讯id',
	'published_ip' => '发布ip',
	'related_information' => '相关信息id',

	//function/model.func.php
	'model_validate_subject' => '标题',
	'model_validate_categories' => '分类',
	'model_validate_subjectimage' => '标题图片',
	'model_validate_choose' => '请选择',
	'model_validate_choose_2' => '请您选择一个',
	'model_validate_input_1' => '请您输入',
	'model_validate_noset' => '您未设置',
	'model_validate_affirm' => '请检查确认',
	'model_validate_input_2' => '您输入的',
	'model_validate_input_3' => '长度不符合要求,目前长度为',
	'model_validate_input_4' => '字符,请保证在',
	'model_validate_input_5' => '字符以内',
	'model_validate_input_6' => '格式不正确,请检查确认',

	//admin/admin_modelcategories.php,
	'model_category_delete' => '删除到废件箱',
	'model_help_categories_add' => '<ul>
			<li>跳转链接不为空的时候，访问该分类的时候，页面会跳转到指定的链接地址。</li>
			<li>通过<u>扩展读取分类设置</u>，您可以设置当前分类下面同时也读取其他分类(比如其子分类)的信息资源。默认只读取本分类自己的信息。</li>
			</ul>',

	//admin/admin_models.php
	'identify_options' => '选定',
	
	//admin/admin_member.php
	'confirm_the_deletion_user_date' => '危险，这将删除该用户所有数据，并且本操作不可恢复，确认删除？',
	'delete_user_date' => '删除该用户所有数据',
	'users_protection_was_not_deleted' => '本用户被保护，不能删除',
	
	//admin/admin_freshhtml.php
	'iswrite_file_error' => '文件不可写, 检查文件属性',
	'iswrite_error' => '目录不可写, 检查目录属性',
	'announcement' => '公告',
	'site_map' => '站点地图',
	'making_create_cache' => '设置保存成功。进入下一步更新索引中，请等待......',
	'making_create_cache_update' => '索引更新成功。进入下一步生成HTML中，请等待......',
	'making_page_cache_update' => '索引页面生成完成。进入下一步更新索引中，请等待......',
	'making_create_cache_havedata' => '索引中有未完成数据。进入下一步生成HTML中，请等待......',
	'freshhtml_making_page_info_0' => '索引中剩余',
	'freshhtml_making_page_info_1' => '个页面，每批(',
	'freshhtml_making_page_info_2' => ')个页面，进入第(',
	'freshhtml_making_page_info_3' => ')批生成html处理中，请等待......',
	
	//admin/admin_makehtml.php
	'page_no_info' => '此页面没内容, 请访问其他页面',
	'make_index_html' => '生成资讯首页HTML页面',
	'make_html_all' => '更新资讯分类HTML页面',
	'make_html_for_itemid' => '更新文章HTML页面',
	'make_index_path' => '首页HTML存放地址<p>默认情况下存放在"系统配置"中设置的资讯HTML存放路径下, 如果要存放其他地方, 请修改对应的相对路径(保证路径可写)</p>',
	'index_domain' => '首页绑定域名(必须以"http:"//开头)<p>如果资讯分类没有绑定域名,则以首页绑定的域名为主, 否则以分类绑定的域名为主</p>',
	'news_cat' => '资讯分类',
	'perlisthtml' => '列表显示条数',
	'update_makeupid' => '是否更新子分类',
	'update_makeupid_yes' => '更新子分类HTML',
	'update_makeupid_no' => '只更新选择的分类HTML'	,
	'make_all_news' => '更新全部资讯文章',
	'admincp_html_note' => '1.此模式只针对资讯频道进行HTML优化.<br />2.如果您是第一次使用此模式, 请先通过此模式对各个分类生成静态化, 防止出现访问错误'
);

?>